local day_length = 30 * 16

-- Config options
-- TUNING.DEBUG_MODE = GetModConfigData("debug_mode")
-- TUNING.OXYGENMETER_COMPACT = GetModConfigData("oxygenmetermode")
TUNING.DEBUG_MODE = false
TUNING.OXYGENMETER_COMPACT = true
TUNING.CITD_BGCOLOURS = { 50 / 255, 100 / 255, 220 / 255 }

-- Oxygen
TUNING.OXYGEN_LOSS_RATE = -100 / 60 -- 100 a minute
TUNING.OXYGEN_EFFECT_RANGE = 8
TUNING.OXYGEN_AIRINESS = 1
TUNING.BUBBLE_OXYGEN_AMOUNT = 10
TUNING.BUBBLE_FLOAT_TIME = 5
TUNING.OXYGEN_THRESH = 0.2

TUNING.PLAYER_OXYGEN = {
	WILSON = 100, -- Default is 100
	WILLOW = 80,
	WOLFGANG = 150,
	WENDY = 80,
	WICKERBOTTOM = 100,
	WOODIE = 150,
	WES = 55,
	WAXWELL = 120,
	WIGFRID = 150,
	WEBBER = 85,
}

-- World
TUNING.MAX_UNDERWATER_ENTRANCES = 2

TUNING.TIDAL_EFFECT_RANGE = 16

TUNING.GEOTHERMAL_VENT_HEAT = 180
TUNING.GEOTHERMAL_VENT_AIR = 30


-- Items
TUNING.HAT_DIVING_PERISHTIME = 10 * day_length
TUNING.HAT_DIVING_PERCENTAGE = 0.8

TUNING.HAT_SNORKEL_PERISHTIME = 8 * day_length
TUNING.HAT_SNORKEL_PERCENTAGE = 0.5

TUNING.PEARL_AMULET_FUEL = 2 * day_length
TUNING.PEARL_AMULET_RATE = 8

-- Monsters
TUNING.SEATENTACLE_THIEF_CHANCE = 0.33

TUNING.JELLYFISH_SPAWN_DELAY = 0.5 * day_length
TUNING.JELLYFISH_SPAWN_VAR = 0.5 * day_length

TUNING.SHRIMP_SPAWN_DELAY = 0.5 * day_length
TUNING.SHRIMP_SPAWN_VAR = 0.5 * day_length

TUNING.CRAB_GROW_TIME = { base = 3 * day_length, random = 2 * day_length }
--TUNING.CRAB_GROW_TIME = {base = 15, random = 5}
TUNING.CRAB_RESPAWN_TIME = 10
TUNING.CRAB_TARGET_DIST = 10

TUNING.TINYCRAB_WALK_SPEED = 10
TUNING.TINYCRAB_DAMAGE = 1
TUNING.TINYCRAB_HEALTH = 25

TUNING.SMALLCRAB_WALK_SPEED = 6
TUNING.SMALLCRAB_DAMAGE = 10
TUNING.SMALLCRAB_HEALTH = 100

TUNING.MEDIUMCRAB_WALK_SPEED = 4
TUNING.MEDIUMCRAB_DAMAGE = 20
TUNING.MEDIUMCRAB_HEALTH = 300

TUNING.LARGECRAB_WALK_SPEED = 2
TUNING.LARGECRAB_DAMAGE = 30
TUNING.LARGECRAB_HEALTH = 700

TUNING.SEA_EEL_WALK_SPEED = 6
TUNING.SEA_EEL_DAMAGE = 35
TUNING.SEA_EEL_ATTACK_PERIOD = 0.5
TUNING.SEA_EEL_HEALTH = 100

TUNING.CLAM_HEALTH = 250
TUNING.CLAM_SPAWN_DELAY = 0.5 * day_length
TUNING.CLAM_SPAWN_VAR = 0.5 * day_length
