--adding new keys and locks
local locks = 1
for _, v in pairs(LOCKS) do
	locks = math.max(v + 1, locks)
end

local keys = 1
for _, v in pairs(KEYS) do
	keys = math.max(v + 1, keys)
end

LOCKS.JUNGLE_DEPTH_1 = locks
KEYS.JUNGLE_DEPTH_1 = keys
LOCKS_KEYS[LOCKS.JUNGLE_DEPTH_1] = { KEYS.JUNGLE_DEPTH_1 }

LOCKS.JUNGLE_DEPTH_2 = locks + 1
KEYS.JUNGLE_DEPTH_2 = keys + 1
LOCKS_KEYS[LOCKS.JUNGLE_DEPTH_2] = { KEYS.JUNGLE_DEPTH_2 }

LOCKS.JUNGLE_DEPTH_3 = locks + 2
KEYS.JUNGLE_DEPTH_3 = keys + 2
LOCKS_KEYS[LOCKS.JUNGLE_DEPTH_3] = { KEYS.JUNGLE_DEPTH_3 }

LOCKS.CIVILIZATION_1 = locks + 3
KEYS.CIVILIZATION_1 = keys + 3
LOCKS_KEYS[LOCKS.CIVILIZATION_1] = { KEYS.CIVILIZATION_1 }

LOCKS.LAND_DIVIDE_1 = locks + 4
KEYS.LAND_DIVIDE_1 = keys + 4
LOCKS_KEYS[LOCKS.LAND_DIVIDE_1] = { KEYS.LAND_DIVIDE_1 }

LOCKS.LAND_DIVIDE_2 = locks + 5
KEYS.LAND_DIVIDE_2 = keys + 5
LOCKS_KEYS[LOCKS.LAND_DIVIDE_2] = { KEYS.LAND_DIVIDE_2 }

LOCKS.LAND_DIVIDE_3 = locks + 6
KEYS.LAND_DIVIDE_3 = keys + 6
LOCKS_KEYS[LOCKS.LAND_DIVIDE_3] = { KEYS.LAND_DIVIDE_3 }

LOCKS.OTHER_JUNGLE_DEPTH_1 = locks + 7
KEYS.OTHER_JUNGLE_DEPTH_1 = keys + 7
LOCKS_KEYS[LOCKS.OTHER_JUNGLE_DEPTH_1] = { KEYS.OTHER_JUNGLE_DEPTH_1 }

LOCKS.OTHER_JUNGLE_DEPTH_2 = locks + 8
KEYS.OTHER_JUNGLE_DEPTH_2 = keys + 8
LOCKS_KEYS[LOCKS.OTHER_JUNGLE_DEPTH_2] = { KEYS.OTHER_JUNGLE_DEPTH_2 }

LOCKS.LOST_JUNGLE_DEPTH_2 = locks + 9
KEYS.LOST_JUNGLE_DEPTH_2 = keys + 9
LOCKS_KEYS[LOCKS.LOST_JUNGLE_DEPTH_2] = { KEYS.LOST_JUNGLE_DEPTH_2 }

LOCKS.ISLAND_1 = locks + 10
KEYS.ISLAND_1 = keys + 10
LOCKS_KEYS[LOCKS.ISLAND_1] = { KEYS.ISLAND_1 }

LOCKS.ISLAND_2 = locks + 11
KEYS.ISLAND_2 = keys + 11
LOCKS_KEYS[LOCKS.ISLAND_2] = { KEYS.ISLAND_2 }

LOCKS.ISLAND_3 = locks + 12
KEYS.ISLAND_3 = keys + 12
LOCKS_KEYS[LOCKS.ISLAND_3] = { KEYS.ISLAND_3 }

LOCKS.ISLAND_4 = locks + 13
KEYS.ISLAND_4 = keys + 13
LOCKS_KEYS[LOCKS.ISLAND_4] = { KEYS.ISLAND_4 }

LOCKS.PINACLE = locks + 14
KEYS.PINACLE = keys + 14
LOCKS_KEYS[LOCKS.PINACLE] = { KEYS.PINACLE }

LOCKS.CIVILIZATION_2 = locks + 15
KEYS.CIVILIZATION_2 = keys + 15
LOCKS_KEYS[LOCKS.CIVILIZATION_2] = { KEYS.CIVILIZATION_2 }

LOCKS.LAND_DIVIDE_4 = locks + 16
KEYS.LAND_DIVIDE_4 = keys + 16
LOCKS_KEYS[LOCKS.LAND_DIVIDE_4] = { KEYS.LAND_DIVIDE_4 }

LOCKS.OTHER_CIVILIZATION_1 = locks + 17
KEYS.OTHER_CIVILIZATION_1 = keys + 17
LOCKS_KEYS[LOCKS.OTHER_CIVILIZATION_1] = { KEYS.OTHER_CIVILIZATION_1 }

LOCKS.OTHER_CIVILIZATION_2 = locks + 18
KEYS.OTHER_CIVILIZATION_2 = keys + 18
LOCKS_KEYS[LOCKS.OTHER_CIVILIZATION_2] = { KEYS.OTHER_CIVILIZATION_2 }

LOCKS.WILD_JUNGLE_DEPTH_1 = locks + 19
KEYS.WILD_JUNGLE_DEPTH_1 = keys + 19
LOCKS_KEYS[LOCKS.WILD_JUNGLE_DEPTH_1] = { KEYS.WILD_JUNGLE_DEPTH_1 }

LOCKS.WILD_JUNGLE_DEPTH_2 = locks + 20
KEYS.WILD_JUNGLE_DEPTH_2 = keys + 20
LOCKS_KEYS[LOCKS.WILD_JUNGLE_DEPTH_2] = { KEYS.WILD_JUNGLE_DEPTH_2 }

LOCKS.ISLAND_5 = locks + 21
KEYS.ISLAND_5 = keys + 21
LOCKS_KEYS[LOCKS.ISLAND_5] = { KEYS.ISLAND_5 }

LOCKS.LAND_DIVIDE_5 = locks + 22
KEYS.LAND_DIVIDE_5 = keys + 22
LOCKS_KEYS[LOCKS.LAND_DIVIDE_5] = { KEYS.LAND_DIVIDE_5 }
----------------------
LOCKS.ISLAND1 = locks + 23
KEYS.ISLAND1 = keys + 23
LOCKS_KEYS[LOCKS.ISLAND1] = { KEYS.ISLAND1 }

LOCKS.ISLAND2 = locks + 24
KEYS.ISLAND2 = keys + 24
LOCKS_KEYS[LOCKS.ISLAND2] = { KEYS.ISLAND2 }

LOCKS.ISLAND3 = locks + 25
KEYS.ISLAND3 = keys + 25
LOCKS_KEYS[LOCKS.ISLAND3] = { KEYS.ISLAND3 }

LOCKS.ISLAND4 = locks + 26
KEYS.ISLAND4 = keys + 26
LOCKS_KEYS[LOCKS.ISLAND4] = { KEYS.ISLAND4 }

LOCKS.ISLAND5 = locks + 27
KEYS.ISLAND5 = keys + 27
LOCKS_KEYS[LOCKS.ISLAND5] = { KEYS.ISLAND5 }

LOCKS.ISLAND6 = locks + 28
KEYS.ISLAND6 = keys + 28
LOCKS_KEYS[LOCKS.ISLAND6] = { KEYS.ISLAND6 }

LOCKS.ISLAND7 = locks + 29
KEYS.ISLAND7 = keys + 29
LOCKS_KEYS[LOCKS.ISLAND7] = { KEYS.ISLAND7 }

LOCKS.ISLAND8 = locks + 30
KEYS.ISLAND8 = keys + 30
LOCKS_KEYS[LOCKS.ISLAND8] = { KEYS.ISLAND8 }

LOCKS.ISLAND9 = locks + 31
KEYS.ISLAND9 = keys + 31
LOCKS_KEYS[LOCKS.ISLAND9] = { KEYS.ISLAND9 }

LOCKS.ISLAND10 = locks + 32
KEYS.ISLAND10 = keys + 32
LOCKS_KEYS[LOCKS.ISLAND10] = { KEYS.ISLAND10 }

LOCKS.ISLAND11 = locks + 33
KEYS.ISLAND11 = keys + 33
LOCKS_KEYS[LOCKS.ISLAND11] = { KEYS.ISLAND11 }