local DecoCreator = require "prefabs/deco_util"

return
-- 墙壁漏洞
    DecoCreator:Create("deco_wallpaper_rip1", "interior_wall_decals", "wall_decals", "1",
        { decal = true, tags = { "NOBLOCK" } }),
    DecoCreator:Create("deco_wallpaper_rip2", "interior_wall_decals", "wall_decals", "2",
        { decal = true, tags = { "NOBLOCK" } }),
    DecoCreator:Create("deco_wallpaper_rip_side1", "interior_wall_decals", "wall_decals", "10",
        { decal = true, tags = { "NOBLOCK" } }),
    DecoCreator:Create("deco_wallpaper_rip_side2", "interior_wall_decals", "wall_decals", "11",
        { decal = true, tags = { "NOBLOCK" }, background = 3 }),
    DecoCreator:Create("deco_wallpaper_rip_side3", "interior_wall_decals", "wall_decals", "8", { tags = { "NOBLOCK" } }),
    DecoCreator:Create("deco_wallpaper_rip_side4", "interior_wall_decals", "wall_decals", "9", { tags = { "NOBLOCK" } }),
    DecoCreator:Create("sewingmachine", "interior_wall_decals_millinery", "wall_decals_millinery", "sewingmachine",
        { decal = true, tags = { "furniture" }, onbuilt = true }),
    DecoCreator:Create("worktable", "interior_wall_decals_millinery", "wall_decals_millinery", "worktable",
        { decal = true, tags = { "furniture" }, onbuilt = true }),
    DecoCreator:Create("picture_1", "interior_wall_decals_millinery", "wall_decals_millinery", "picture1_sidewall",
        { decal = true }),
    DecoCreator:Create("picture_2", "interior_wall_decals_millinery", "wall_decals_millinery", "picture2_sidewall",
        { decal = true }),
    DecoCreator:Create("hat_lamp_side", "interior_wall_decals_millinery", "wall_decals_millinery", "sconce_sidewall",
        { decal = true }),
    DecoCreator:Create("hat_lamp_front", "interior_wall_decals_millinery", "wall_decals_millinery", "sconce_backwall",
        { decal = true }),
    DecoCreator:Create("hatbox1", "interior_wall_decals_millinery", "wall_decals_millinery", "hatbox1", { decal = true }),
    DecoCreator:Create("hatbox2", "interior_wall_decals_millinery", "wall_decals_millinery", "hatbox2", { decal = true }),

    -- weapon store
    DecoCreator:Create("shield_axes", "interior_wall_decals_weapons", "wall_decals_weapons", "shield_axes",
        { decal = true }),
    DecoCreator:Create("shield_spears", "interior_wall_decals_weapons", "wall_decals_weapons", "shield_spears",
        { decal = true }),
    DecoCreator:Create("spears_sidewall", "interior_wall_decals_weapons", "wall_decals_weapons", "spears_sidewall",
        { decal = true }),
    DecoCreator:Create("shield_sidewall", "interior_wall_decals_weapons", "wall_decals_weapons", "shield_sidewall",
        { decal = true }),
    DecoCreator:Create("wall_light1", "interior_wall_decals", "wall_decals", "6", { decal = true, light = true }),
    DecoCreator:Create("wall_deco_truss1", "interior_wall_decals", "wall_decals", "5",
        { scale = { x = 1.12, y = 1, z = 1 } }),
    DecoCreator:Create("light_dust_fx", "light_dust_fx", "light_dust_fx", "idle",
        { loopanim = true, tags = { "NOBLOCK" } }),

    -- hoofspa
    DecoCreator:Create("deco_valence", "interior_wall_decals_hoofspa", "wall_decals_hoofspa", "vallance_1pc",
        { decal = true, background = 3 }),
    DecoCreator:Create("wall_mirror", "interior_wall_mirror", "wall_mirror", "idle",
        { background = 3, followlight = true, mirror = true }),
    DecoCreator:Create("wall_light_hoofspa", "interior_wall_decals_hoofspa", "wall_decals_hoofspa", "sconce_sidewall",
        { light = DecoCreator:GetLights().SMALL }),
    -- DecoCreator:Create("wall_light_hoofspa", "interior_wall_decals_hoofspa", "wall_decals_hoofspa", "sconce_backwall",
    --     { light = DecoCreator:GetLights().SMALL }), --两个一样的名字？

    -- ruins
    DecoCreator:Create("deco_ruins_crack_roots1", "interior_wall_decals_ruins", "interior_wall_decals_ruins", "hole_1",
        { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_crack_roots2", "interior_wall_decals_ruins", "interior_wall_decals_ruins", "hole_2",
        { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_crack_roots3", "interior_wall_decals_ruins", "interior_wall_decals_ruins", "roots_1",
        { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_crack_roots4", "interior_wall_decals_ruins", "interior_wall_decals_ruins", "roots_2",
        { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_roots1", "interior_wall_decals_ruins", "interior_wall_decals_ruins", "vines_1",
        { decal = true, background = 2 }),
    DecoCreator:Create("deco_ruins_roots2", "interior_wall_decals_ruins", "interior_wall_decals_ruins", "vines_2",
        { decal = true, background = 2 }),
    DecoCreator:Create("deco_ruins_roots3", "interior_wall_decals_ruins", "interior_wall_decals_ruins", "vines_3",
        { decal = true, background = 2 }),
    DecoCreator:Create("deco_ruins_pigking_relief", "interior_wall_decals_ruins", "interior_wall_decals_ruins",
        "relief_king", { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_pigman_relief2", "interior_wall_decals_ruins", "interior_wall_decals_ruins",
        "relief_happy", { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_pigqueen_relief", "interior_wall_decals_ruins", "interior_wall_decals_ruins",
        "relief_queen", { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_pigman_relief1", "interior_wall_decals_ruins", "interior_wall_decals_ruins",
        "relief_confused", { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_pigman_relief3", "interior_wall_decals_ruins", "interior_wall_decals_ruins",
        "relief_surprise", { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_pigman_relief_side", "interior_wall_decals_ruins", "interior_wall_decals_ruins",
        "relief_sidewall", { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_pigman_relief4", "interior_wall_decals_ruins", "interior_wall_decals_ruins",
        "relief_head", { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_wallstrut", "interior_wall_decals_ruins", "interior_wall_decals_ruins", "support_side",
        { decal = true }),
    DecoCreator:Create("deco_ruins_walltorch", "interior_wall_decals_ruins", "interior_wall_decals_ruins",
        "sconce_metal_sidewall", { decal = true, background = 3 }),


    -- THE BLUE RUINS ART
    DecoCreator:Create("deco_ruins_pigking_relief_blue", "interior_wall_decals_ruins_blue", "interior_wall_decals_ruins",
        "relief_king", { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_pigman_relief2_blue", "interior_wall_decals_ruins_blue", "interior_wall_decals_ruins",
        "relief_happy", { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_pigqueen_relief_blue", "interior_wall_decals_ruins_blue", "interior_wall_decals_ruins",
        "relief_queen", { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_pigman_relief1_blue", "interior_wall_decals_ruins_blue", "interior_wall_decals_ruins",
        "relief_confused", { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_pigman_relief3_blue", "interior_wall_decals_ruins_blue", "interior_wall_decals_ruins",
        "relief_surprise", { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_pigman_relief_side_blue", "interior_wall_decals_ruins_blue",
        "interior_wall_decals_ruins", "relief_sidewall", { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_pigman_relief4_blue", "interior_wall_decals_ruins_blue", "interior_wall_decals_ruins",
        "relief_head", { decal = true, background = 1 }),


    --   DecoCreator:Create("deco_ruins_fountain", "pig_ruins_well", "pig_ruins_well", "idle_full",                                      {loopanim=true, decal=true, physics="pond_physics", minimapicon="pig_ruins_well.png"}),
    DecoCreator:Create("deco_ruins_wallcrumble_1", "interior_wall_decals_ruins", "interior_wall_decals_ruins", "2",
        { decal = true, background = 1 }),
    DecoCreator:Create("deco_ruins_wallcrumble_side_1", "interior_wall_decals_ruins", "interior_wall_decals_ruins", "1",
        { decal = true }),
    DecoCreator:Create("deco_ruins_writing1", "interior_wall_decals_ruins", "interior_wall_decals_ruins", "latin_5",
        { decal = true, background = 1, prefabname = "pig_latin_1" }),

    -- florist
    DecoCreator:Create("deco_wallpaper_florist_rip1", "interior_wall_decals_florist", "interior_wall_decals_florist",
        "hole_1", { decal = true, background = 1 }),
    DecoCreator:Create("deco_wallpaper_florist_rip2", "interior_wall_decals_florist", "interior_wall_decals_florist",
        "hole_2", { decal = true, background = 1 }),
    DecoCreator:Create("deco_wallpaper_florist_rip3", "interior_wall_decals_florist", "interior_wall_decals_florist",
        "hole_3", { decal = true, background = 1 }),
    DecoCreator:Create("deco_wallpaper_florist_rip4", "interior_wall_decals_florist", "interior_wall_decals_florist",
        "hole_4", { decal = true, background = 1 }),
    DecoCreator:Create("deco_wallpaper_florist_side_rip1", "interior_wall_decals_florist", "interior_wall_decals_florist",
        "hole_5_sidewall", { decal = true }),
    DecoCreator:Create("deco_wallpaper_florist_side_rip2", "interior_wall_decals_florist", "interior_wall_decals_florist",
        "hole_6_sidewall", { decal = true }),
    DecoCreator:Create("deco_deli_meatrack", "ceiling_decor", "ceiling_decor", "meatrack_idle", { loopanim = true }),
    DecoCreator:Create("deco_deli_basket", "ceiling_decor", "ceiling_decor", "wire_basket_idle", { loopanim = true }),
    DecoCreator:Create("deco_general_hangingscale", "ceiling_decor", "ceiling_decor", "scale_idle", { loopanim = true }),
    DecoCreator:Create("deco_general_hangingpans", "ceiling_decor", "ceiling_decor", "pans_idle", { loopanim = true }),
    DecoCreator:Create("deco_general_trough", "interior_wall_decals_florist", "interior_wall_decals_florist",
        "tiered_trough", { decal = true }),

    --arcane
    DecoCreator:Create("closed_chest", "interior_wall_decals_arcane", "wall_decals_arcane", "chest_closed",
        { decal = true }),
    DecoCreator:Create("open_chest", "interior_wall_decals_arcane", "wall_decals_arcane", "chest_open", { decal = true }),
    DecoCreator:Create("containers", "interior_wall_decals_arcane", "wall_decals_arcane", "containers", { decal = true }),
    DecoCreator:Create("deco_arcane_bookshelf", "interior_wall_decals_arcane", "wall_decals_arcane", "bookcase_backwall",
        { decal = true }),
    DecoCreator:Create("mirror_backwall", "interior_wall_decals_arcane", "wall_decals_arcane", "mirror_backwall",
        { decal = true }),


    --BAT CAVE
    DecoCreator:Create("deco_cave_beam_room", "interior_wall_decals_batcave", "interior_wall_decals_cave", "pillar_front",
        { decal = true, physics = "big_post_physics", workable = true, minimapicon = "vamp_cave_pillar.png" }),
    DecoCreator:Create("deco_cave_cornerbeam", "interior_wall_decals_batcave", "interior_wall_decals_cave",
        "pillar_corner", { decal = true, background = 3, tags = { "cornerpost" } }),
    DecoCreator:Create("deco_cave_pillar_side", "interior_wall_decals_batcave", "interior_wall_decals_cave",
        "pillar_sidewall", { decal = true }),
    DecoCreator:Create("deco_cave_ceiling_trim", "interior_wall_decals_batcave", "interior_wall_decals_cave",
        "ceiling_trim_1"),
    DecoCreator:Create("deco_cave_ceiling_trim_2", "interior_wall_decals_batcave", "interior_wall_decals_cave",
        "ceiling_trim_2", { decal = true, background = 3 }),
    DecoCreator:Create("deco_cave_ceiling_trim_3", "interior_wall_decals_batcave", "interior_wall_decals_cave",
        "ceiling_trim_3"),
    DecoCreator:Create("deco_cave_floor_trim", "interior_wall_decals_batcave", "interior_wall_decals_cave",
        "floor_trim_1", { decal = true, background = 3 }),
    DecoCreator:Create("deco_cave_floor_trim_2", "interior_wall_decals_batcave", "interior_wall_decals_cave",
        "floor_trim_2", { decal = true, background = 3 }),
    DecoCreator:Create("deco_cave_floor_trim_front", "interior_wall_decals_batcave", "interior_wall_decals_cave",
        "floor_trim_3"),
    DecoCreator:Create("deco_cave_stalactite", "interior_wall_decals_batcave", "interior_wall_decals_cave", "stalactite"),
    DecoCreator:Create("deco_cave_bat_burrow", "interior_wall_decals_batcave", "interior_wall_decals_cave", "bat_burrow",
        {
            decal = true,
            physics = "pond_physics",
            prefabname = "deco_cave_bat_burrow",
            minimapicon =
            "vamp_cave_burrow.png"
        }),

    --ANT HIVE
    DecoCreator:Create("deco_hive_beam_room", "interior_wall_decals_antcave", "interior_wall_decals_antcave",
        "pillar_front", {
            decal = true,
            physics = "big_post_physics",
            workable = true,
            minimapicon =
            "vamp_cave_pillar.png"
        }),
    DecoCreator:Create("deco_hive_cornerbeam", "interior_wall_decals_antcave", "interior_wall_decals_antcave",
        "pillar_corner", { decal = true, background = 3, tags = { "cornerpost" } }),
    DecoCreator:Create("deco_hive_pillar_side", "interior_wall_decals_antcave", "interior_wall_decals_antcave",
        "pillar_sidewall", { decal = true }),
    DecoCreator:Create("deco_hive_floor_trim", "interior_wall_decals_antcave", "interior_wall_decals_antcave",
        "floor_trim_1"),
    DecoCreator:Create("deco_hive_beam_broken_room", "interior_wall_decals_antcave", "interior_wall_decals_antcave",
        "pillar_front_crumble_idle", { decal = true, physics = "big_post_physics", minimapicon = "vamp_cave_pillar.png" }),
    DecoCreator:Create("deco_hive_stalactite", "interior_wall_decals_antcave", "interior_wall_decals_antcave",
        "stalactite"),
    DecoCreator:Create("deco_hive_broken_pillar", "interior_wall_decals_antcave", "interior_wall_decals_antcave",
        "pillar_broken"),
    DecoCreator:Create("deco_hive_debris", "interior_wall_decals_antcave", "interior_wall_decals_antcave", "rock_debris"),
    DecoCreator:Create("deco_cave_honey_drip_1", "interior_wall_decals_antcave", "interior_wall_decals_antcave",
        "honey_wall_1", { decal = true, background = 3 }),
    DecoCreator:Create("deco_cave_ceiling_drip_2", "interior_wall_decals_antcave", "interior_wall_decals_antcave",
        "honey_floor_1", { decal = true, background = 3 }),
    DecoCreator:Create("deco_cave_honey_drip_side_1", "interior_wall_decals_antcave", "interior_wall_decals_antcave",
        "honey_wall_2", { decal = true, background = 3 }),
    DecoCreator:Create("deco_cave_honey_drip_side_2", "interior_wall_decals_antcave", "interior_wall_decals_antcave",
        "honey_floor_2", { decal = true, background = 3 }),

    --deli
    DecoCreator:Create("deco_deli_stove_metal_side", "interior_wall_decals_deli", "wall_decals_deli", "stove_sidewall",
        { decal = true }),
    DecoCreator:Create("deco_deli_wallpaper_rip_side1", "interior_wall_decals_deli", "wall_decals_deli", "hole_5",
        { decal = true }),
    DecoCreator:Create("deco_deli_wallpaper_rip_side2", "interior_wall_decals_deli", "wall_decals_deli", "hole_6",
        { decal = true }),
    DecoCreator:Create("deco_produce_menu_side", "interior_wall_decals_deli", "wall_decals_deli", "menu_sidewall",
        { decal = true }),
    DecoCreator:Create("deco_produce_menu", "interior_wall_decals_deli", "wall_decals_deli", "menu_front",
        { decal = true }),


    -- city hall
    DecoCreator:Create("deco_cityhall_picture1", "interior_wall_decals_mayorsoffice", "wall_decals_mayorsoffice",
        "picture1_sidewall", { decal = true }),
    DecoCreator:Create("deco_cityhall_picture2", "interior_wall_decals_mayorsoffice", "wall_decals_mayorsoffice",
        "picture2_sidewall", { decal = true }),
    DecoCreator:Create("deco_cityhall_bookshelf", "interior_wall_decals_mayorsoffice", "wall_decals_mayorsoffice",
        "bookcase_backwall", { decal = true }),
    DecoCreator:Create("deco_cityhall_pillar", "interior_wall_decals_mayorsoffice", "wall_decals_mayorsoffice",
        "pillar_round_corner", { decal = true, loopanim = true, light = DecoCreator:GetLights().SMALL }),
    DecoCreator:Create("window_mayorsoffice", "window_mayorsoffice", "window_mayorsoffice", "day_loop",
        { loopanim = true, decal = true, background = 3, curtains = true }),
    DecoCreator:Create("deco_cityhall_desk", "interior_wall_decals_mayorsoffice", "wall_decals_mayorsoffice", "desk",
        { light = DecoCreator:GetLights().MED, physics = "desk_physics" }),

    -- palace
    DecoCreator:Create("window_palace", "window_palace", "window_palace", "day_loop",
        { loopanim = true, decal = true, background = 3, curtains = true }),
    DecoCreator:Create("window_palace_stainglass", "window_palace_stainglass", "window_palace_stainglass", "day_loop",
        { loopanim = true, decal = true, background = 3, curtains = true }),
    DecoCreator:Create("deco_palace_banner_big_front", "interior_wall_decals_palace", "wall_decals_palace",
        "banner_lg_front", { decal = true }),
    DecoCreator:Create("deco_palace_banner_big_sidewall", "interior_wall_decals_palace", "wall_decals_palace",
        "banner_lg_sidewall", { decal = true }),
    DecoCreator:Create("deco_palace_banner_small_front", "interior_wall_decals_palace", "wall_decals_palace",
        "banner_sml_front", { decal = true }),
    DecoCreator:Create("deco_palace_banner_small_sidewall", "interior_wall_decals_palace", "wall_decals_palace",
        "banner_sml_sidewall", { decal = true }),
    DecoCreator:Create("deco_palace_throne", "interior_wall_decals_palace", "wall_decals_palace", "throne",
        { decal = true, physics = "chair_physics" }),
    DecoCreator:Create("deco_displaycase", "interior_wall_decals_antiquities", "wall_decals_antiquities",
        "displayshelf_corner", { decal = true, physics = "post_physics" }),
    DecoCreator:Create("deco_palace_plant", "interior_wall_decals_palace", "wall_decals_palace", "plant",
        { decal = true }),

    -- Bank
    DecoCreator:Create("deco_bank_clock1_side", "interior_decor", "interior_decor", "clock1_sidewall", { decal = true }),
    DecoCreator:Create("deco_bank_clock2_side", "interior_decor", "interior_decor", "clock2_sidewall", { decal = true }),
    DecoCreator:Create("deco_bank_clock3_side", "interior_decor", "interior_decor", "clock3_sidewall", { decal = true }),
    DecoCreator:Create("deco_bank_vault", "interior_unique", "interior_unique", "vault", { decal = true }),

    -- Tinker
    DecoCreator:Create("deco_rollholder", "interior_floor_decor", "interior_floor_decor", "rollholder",
        { physics = "post_physics", tags = { "furniture" }, onbuilt = true }),
    DecoCreator:Create("deco_rollholder_front", "interior_floor_decor", "interior_floor_decor", "rollholder_front",
        { physics = "sofa_physics", tags = { "furniture" }, onbuilt = true }),
    DecoCreator:Create("deco_filecabinet", "interior_floor_decor", "interior_floor_decor", "filecabinet",
        { physics = "post_physics", tags = { "furniture" }, onbuilt = true }),
    DecoCreator:Create("deco_rollchest", "interior_floor_decor", "interior_floor_decor", "chest_open",
        { physics = "post_physics", tags = { "furniture" }, onbuilt = true }),
    DecoCreator:Create("deco_worktable", "interior_floor_decor", "interior_floor_decor", "worktable",
        { physics = "sofa_physics", tags = { "furniture" }, onbuilt = true }),
    DecoCreator:Create("grotto_pillar_bug", "interior_wall_grottogub_cave", "interior_wall_grottogub_cave",
        "pillar_front",
        { decal = true, physics = "big_post_physics", workable = true, minimapicon = "grotto_pillar_bug.png", scale = { x = 1.5, y = 1.5, z = 1.5 } }),
    DecoCreator:Create("deco_ruins_cornerbeam_blue", "interior_wall_decals_ruins_blue", "interior_wall_decals_ruins",
        "pillar_corner", { decal = true, background = 3, tags = { "cornerpost" } }),
    DecoCreator:Create("deco_ruins_cornerbeam_heavy_blue", "interior_wall_decals_ruins_blue",
        "interior_wall_decals_ruins", "pillar_corner_lg", { decal = true, background = 3, tags = { "cornerpost" } }),
    DecoCreator:Create("deco_ruins_beam_heavy_blue", "interior_wall_decals_ruins_blue", "interior_wall_decals_ruins",
        "pillar_side_lg", { decal = true, background = 3 }),
    DecoCreator:Create("deco_ruins_beam_blue", "interior_wall_decals_ruins_blue", "interior_wall_decals_ruins",
        "pillar_front", { decal = true }),
    DecoCreator:Create("deco_ruins_beam_room_blue", "interior_wall_decals_ruins_blue", "interior_wall_decals_ruins",
        "pillar_front", { decal = true, physics = "post_physics", workable = true, minimapicon = "pig_ruins_pillar.png" }),
    DecoCreator:Create("deco_ruins_beam_room_broken_blue", "interior_wall_decals_ruins_blue",
        "interior_wall_decals_ruins", "pillar_broken",
        { decal = true, physics = "post_physics", minimapicon = "pig_ruins_pillar.png" }),
    DecoCreator:Create("deco_ruins_beam_broken_blue", "interior_wall_decals_ruins_blue", "interior_wall_decals_ruins",
        "pillar_broken", { decal = true, background = 3 })
