require "map/terrain"

-- 限制这些植物生成的地皮，禁止在表里的地皮里生成
terrain.filter.peach_tree1 = { WORLD_TILES.ROAD, WORLD_TILES.WOODFLOOR, WORLD_TILES.CARPET, GROUND
    .CHECKER, WORLD_TILES.ROCKY, WORLD_TILES.MARSH }
terrain.filter.peach_tree2 = { WORLD_TILES.ROAD, WORLD_TILES.WOODFLOOR, WORLD_TILES.CARPET, GROUND
    .CHECKER, WORLD_TILES.ROCKY, WORLD_TILES.MARSH }
terrain.filter.peach_tree3 = { WORLD_TILES.ROAD, WORLD_TILES.WOODFLOOR, WORLD_TILES.CARPET, GROUND
    .CHECKER, WORLD_TILES.ROCKY, WORLD_TILES.MARSH }
