--turtle----------------------
------------------------------
TUNING.SPIKY_TURTLE_TFC = {}
TUNING.SPIKY_TURTLE_TFC.HEALTH = 1200
TUNING.SPIKY_TURTLE_TFC.KEEPDIST = 30
TUNING.SPIKY_TURTLE_TFC.WALKSPEED = 3
TUNING.SPIKY_TURTLE_TFC.TARGET_DIST = 25
--melee
TUNING.SPIKY_TURTLE_TFC.DAMAGE = 45
TUNING.SPIKY_TURTLE_TFC.RANGE = 4
TUNING.SPIKY_TURTLE_TFC.ATTACK_PERIOD = 1.7
--slides
TUNING.SPIKY_TURTLE_TFC.SLIDEDAMAGE = 45
TUNING.SPIKY_TURTLE_TFC.SLIDE_RADIUS = 3
TUNING.SPIKY_TURTLE_TFC.SLIDES_ALLOWED = 5
--hider
TUNING.SPIKY_TURTLE_TFC.SHELL_REQ_DAMAGE = 350
TUNING.SPIKY_TURTLE_TFC.INSHELL_TIME = 5
TUNING.SPIKY_TURTLE_TFC.SHIELDED_DAMAGE_REDUCTION = 0.95

--scorpion------------------------
----------------------------------
TUNING.STRANGE_SCORPION_TFC = {}
TUNING.STRANGE_SCORPION_TFC.HEALTH = 1200
TUNING.STRANGE_SCORPION_TFC.RUNSPEED = 3
TUNING.STRANGE_SCORPION_TFC.TARGET_DIST = 25
TUNING.STRANGE_SCORPION_TFC.KEEPDIST = 30
--melee
TUNING.STRANGE_SCORPION_TFC.DAMAGE = 45
TUNING.STRANGE_SCORPION_TFC.RANGE = 4
TUNING.STRANGE_SCORPION_TFC.ATTACK_PERIOD = 1.5
--range
TUNING.STRANGE_SCORPION_TFC.RANGE_ATTACK_PERIOD = 10
TUNING.STRANGE_SCORPION_TFC.SPITRANGE = 20
TUNING.STRANGE_SCORPION_TFC.SPITDAMAGE = 5
--splash
TUNING.STRANGE_SCORPION_TFC.STICKY_SPIT = true
TUNING.STRANGE_SCORPION_TFC.SPLASHRADIUS = 3
TUNING.STRANGE_SCORPION_TFC.SPLASHDAMAGE = 40
--spread
TUNING.STRANGE_SCORPION_TFC.SPREAD_TARGETS = 3

--piggy---------------------------
----------------------------------
TUNING.HATTY_PIGGY_TFC = {}
TUNING.HATTY_PIGGY_TFC.HEALTH = 400
TUNING.HATTY_PIGGY_TFC.RUNSPEED = 10
TUNING.HATTY_PIGGY_TFC.TARGET_DIST = 25
TUNING.HATTY_PIGGY_TFC.KEEPDIST = 30
TUNING.HATTY_PIGGY_TFC.SHARE_DIST = 25
--melee
TUNING.HATTY_PIGGY_TFC.DAMAGE = 45
TUNING.HATTY_PIGGY_TFC.RANGE = 2
TUNING.HATTY_PIGGY_TFC.ATTACK_PERIOD = 1.5
--charge
TUNING.HATTY_PIGGY_TFC.CHARGE_RECHARGE = 5
TUNING.HATTY_PIGGY_TFC.DAMAGE = 45

--elemental-------------------------
------------------------------------
TUNING.FLAME_ELEMENTAL_TFC = {}
TUNING.FLAME_ELEMENTAL_TFC.HEALTH = 400
--attack
TUNING.FLAME_ELEMENTAL_TFC.DAMAGE = 7
TUNING.FLAME_ELEMENTAL_TFC.RANGE = 15
TUNING.FLAME_ELEMENTAL_TFC.ATTACK_PERIOD = 0.7
--blast
TUNING.FLAME_ELEMENTAL_TFC.BLAST_DAMAGE = 250
TUNING.FLAME_ELEMENTAL_TFC.BLAST_RADIUS = 5

--lizardmen-------------------------
------------------------------------
TUNING.LIZARDMAN_TFC = {}
TUNING.LIZARDMAN_TFC.TARGET_DIST = 12
TUNING.LIZARDMAN_TFC.KEEP_TARGET_DIST = 20
TUNING.LIZARDMAN_TFC.DAMAGE = 25
TUNING.LIZARDMAN_TFC.ATTACK_PERIOD = 2.5
TUNING.LIZARDMAN_TFC.SPEED = 6
TUNING.LIZARDMAN_TFC.HEALTH = 680
TUNING.LIZARDMAN_TFC.SHARE_TARGET_DIST = 20
TUNING.LIZARDMAN_TFC.ATTACK_RANGE = 4
TUNING.LIZARDMAN_TFC.DIST_ATTACK_RANGE = 16
TUNING.LIZARDMAN_TFC.TORNS_DAMAGE = 5
TUNING.LIZARDMAN_TFC.BANNER_RECHARGE = 15

--boarilla--------------------------
------------------------------------
TUNING.SPIKY_MONKEY_TFC = {}
TUNING.SPIKY_MONKEY_TFC.SPEED = 7.5
TUNING.SPIKY_MONKEY_TFC.HEALTH = 1200
TUNING.SPIKY_MONKEY_TFC.TARGET_DIST = 12
TUNING.SPIKY_MONKEY_TFC.KEEP_TARGET_DIST = 20
--combat
TUNING.SPIKY_MONKEY_TFC.DAMAGE = 65
TUNING.SPIKY_MONKEY_TFC.ATTACK_PERIOD = 2.5
TUNING.SPIKY_MONKEY_TFC.ATTACK_RANGE = 4
--shield
TUNING.SPIKY_MONKEY_TFC.SHELL_REQ_DAMAGE = 350
TUNING.SPIKY_MONKEY_TFC.INSHELL_TIME = 5
TUNING.SPIKY_MONKEY_TFC.SHIELDED_DAMAGE_REDUCTION = 0.95
--slam
TUNING.SPIKY_MONKEY_TFC.SLAM_RECHARGE = 5
TUNING.SPIKY_MONKEY_TFC.SLAM_RADIUS = 5
TUNING.SPIKY_MONKEY_TFC.SLAM_DAMAGE = 100

local dm = 1.5
TUNING.FORGE_ITEM_PACK = {
    GOLEM = { HEALTH = 1, RUNSPEED = 0, DAMAGE = 25, HIT_RANGE = 9, ATTACK_PERIOD = 2, LIFE_TIME = 50 },
    TFWP_LAVA_DART = { DAMAGE = 20 * dm, COOLDOWN = 18, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, DISABLE_RECIPE = false },
    TFWP_LAVA_HAMMER = { DAMAGE = 20 * dm, ALT_DAMAGE = 30 * dm / TUNING.ELECTRIC_DAMAGE_MULT, ALT_RADIUS = 4.1, COOLDOWN = 18, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, WORKABLE_DMG = 4, DISABLE_RECIPE = false },
    RILEDLUCY = { DAMAGE = 20 * dm, ALT_DAMAGE = 30 * dm, WORKABLE_DMG = 4, DISABLE_RECIPE = false },
    TFWP_SPEAR_GUNG = { DAMAGE = 25 * dm, ALT_DAMAGE = 25 * dm, ALT_DIST = 6.5, ALT_WIDTH = 3.25, COOLDOWN = 12, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, WORKABLE_DMG = 4, DISABLE_RECIPE = false },
    TFWP_HEALING_STAFF = { DAMAGE = 10 * dm, COOLDOWN = 24, DURATION = 10, HEAL_RATE = 6, RANGE = 4.1, SCALE_RNG = { 30, 40 }, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, DISABLE_RECIPE = false },
    TFWP_DRAGON_DART = { DAMAGE = 25 * dm, ALT_DAMAGE = 50 * dm, COOLDOWN = 18, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, DISABLE_RECIPE = false },
    TFWP_INFERNAL_STAFF = { DAMAGE = 25 * dm, ALT_DAMAGE = { base = 200 * dm, center_mult = 0.25 }, ALT_RADIUS = 4.1, COOLDOWN = 24, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, WORKABLE_DMG = 8, DISABLE_RECIPE = false },
    TFWP_SPEAR_LANCE = { DAMAGE = 30 * dm, ALT_DAMAGE = 75 * dm, ALT_RANGE = 16, ALT_RADIUS = 2.05, COOLDOWN = 12, DURABILITY = { AMOUNT = 0, CONSUMPTION_SPECIAL = 0.5 }, WORKABLE_DMG = 6, DISABLE_RECIPE = false },
    TFWP_CONTROL_BOOK = { DAMAGE = 15 * dm, COOLDOWN = 18, DURATION = 10, ALT_RADIUS = 4.1, DURABILITY = { AMOUNT = 0, CONSUMPTION_SPECIAL = 0.5 }, DISABLE_RECIPE = false },
    TFWP_SUMMON_BOOK = { DAMAGE = 15 * dm, COOLDOWN = 18, DURATION = 10, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, DISABLE_RECIPE = false },
    TFWP_FIRE_BOMB = { DAMAGE = 15 * dm, ALT_DAMAGE = 75 * dm, PROC_DAMAGE = 100 * dm, COOLDOWN = 6, ALT_RANGE = 8, HORIZONTAL_SPEED = 20, GRAVITY = -30, CHARGE_HITS_1 = 7, CHARGE_HITS_2 = 10, MAXIMUM_CHARGE_HITS = 13, CHARGE_DECAY_TIME = 5, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, WORKABLE_DMG = 4, DISABLE_RECIPE = false },
    TFWP_HEAVY_SWORD = { DAMAGE = 30 * dm, HELMSPLIT_DAMAGE = 100 * dm, PARRY_DURATION = 5, COOLDOWN = 12, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, DISABLE_RECIPE = false },
    RET_DATA = {
        fossil = { "aoecctarget", 2 },
        elemental = { "aoesummontarget", 1 },
        hammer = { "aoehostiletarget", 0.9 },
        tfwp_healing_staff = { "aoefriendlytarget", 0.9 },
        fireballstaff = { "aoehostiletarget", 0.7 },
        tfwp_spear_lance = { "aoesmallhostiletarget", 1 },
        tfwp_fire_bomb = { "aoesmallhostiletarget", 1 },
        tfwp_heavy_sword = { "aoehostiletarget", 0.9 }
    }
}

TUNING.FORGE_ITEM_PACK.GOLEM.DAMAGE = 25 * dm
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_HAMMER.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_HAMMER.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_HAMMER.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_HAMMER.COOLDOWN = 18
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_HAMMER.DAMAGE = 20 * dm
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_HAMMER.ALT_DAMAGE = 30 * dm / TUNING.ELECTRIC_DAMAGE_MULT;
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_GUNG.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_GUNG.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_GUNG.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_GUNG.COOLDOWN = 12
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_GUNG.DAMAGE = 25 * dm
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_GUNG.ALT_DAMAGE = 25 * dm
TUNING.FORGE_ITEM_PACK.TFWP_HEALING_STAFF.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_HEALING_STAFF.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_HEALING_STAFF.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_HEALING_STAFF.COOLDOWN = 24
TUNING.FORGE_ITEM_PACK.TFWP_HEALING_STAFF.DURATION = 10
TUNING.FORGE_ITEM_PACK.TFWP_HEALING_STAFF.HEAL_RATE = 6
TUNING.FORGE_ITEM_PACK.TFWP_HEALING_STAFF.DAMAGE = 10 * dm
TUNING.FORGE_ITEM_PACK.TFWP_DRAGON_DART.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_DRAGON_DART.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_DRAGON_DART.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_DRAGON_DART.COOLDOWN = 18
TUNING.FORGE_ITEM_PACK.TFWP_DRAGON_DART.DAMAGE = 25 * dm
TUNING.FORGE_ITEM_PACK.TFWP_DRAGON_DART.ALT_DAMAGE = 50 * dm
TUNING.FORGE_ITEM_PACK.TFWP_INFERNAL_STAFF.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_INFERNAL_STAFF.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_INFERNAL_STAFF.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_INFERNAL_STAFF.COOLDOWN = 24
TUNING.FORGE_ITEM_PACK.TFWP_INFERNAL_STAFF.DAMAGE = 25 * dm
TUNING.FORGE_ITEM_PACK.TFWP_INFERNAL_STAFF.ALT_DAMAGE.base = 200 * dm
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_LANCE.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_LANCE.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_LANCE.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_LANCE.COOLDOWN = 12
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_LANCE.DAMAGE = 30 * dm
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_LANCE.ALT_DAMAGE = 75 * dm
TUNING.FORGE_ITEM_PACK.TFWP_CONTROL_BOOK.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_CONTROL_BOOK.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_CONTROL_BOOK.COOLDOWN = 18
TUNING.FORGE_ITEM_PACK.TFWP_CONTROL_BOOK.DAMAGE = 15 * dm
TUNING.FORGE_ITEM_PACK.TFWP_SUMMON_BOOK.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_SUMMON_BOOK.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_SUMMON_BOOK.COOLDOWN = 18
TUNING.FORGE_ITEM_PACK.TFWP_SUMMON_BOOK.DAMAGE = 15 * dm
TUNING.FORGE_ITEM_PACK.TFWP_FIRE_BOMB.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_FIRE_BOMB.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_FIRE_BOMB.COOLDOWN = 5
TUNING.FORGE_ITEM_PACK.TFWP_FIRE_BOMB.DAMAGE = 15 * dm
TUNING.FORGE_ITEM_PACK.TFWP_FIRE_BOMB.ALT_DAMAGE = 75 * dm
TUNING.FORGE_ITEM_PACK.TFWP_FIRE_BOMB.PROC_DAMAGE = 100 * dm
TUNING.FORGE_ITEM_PACK.TFWP_HEAVY_SWORD.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_HEAVY_SWORD.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_HEAVY_SWORD.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_HEAVY_SWORD.COOLDOWN = 12
TUNING.FORGE_ITEM_PACK.TFWP_HEAVY_SWORD.DAMAGE = 30 * dm
TUNING.FORGE_ITEM_PACK.TFWP_HEAVY_SWORD.HELMSPLIT_DAMAGE = 100 * dm
