PrefabFiles = {
    "artic_flower",        --花
    "beaverskin",          --海狸皮
    "beavertorch",         --海狸火炬
    "cave_entrance_frost", --洞穴入口
    "frosttocave",         --洞穴隧道
    "cave_exit_frost",     --洞穴出口


    "topiary",
    "lawnornaments",
    "hedge",
    "clippings",
    "city_lamp",
    "hamlet_cones",
    "securitycontract",
    "city_hammer",
    "magnifying_glass",
    "pigbandit",

    "pigman_shopkeeper_desk",
    "shop_pedestals",
    "shelf",
    "shelf_slot",
    "trinkets_giftshop",
    "key_to_city",
    "player_house_kits",

    "pighouse_city",
    "pig_guard_tower",
    "armor_metal",
    "reconstruction_project",
    "water_spray",
    "water_pipe",
    "sprinkler1",
    "smelter",
    "halberd",
    "billsnow",
    "giantsnow",
    "snowman_lamp",
    "bear",
    "ice_deer",
    "mammoth",
    "bearden",
    "snowitem",
    "snow_dune",
    "snow_castle",
    "cratesnow",
    "snowpile1",
    "snowbigball",
    "snowbeetle",
    "snowspider_spike",
    "snowspiderden",
    "snowberrybush",
    "snowspider",
    "snowspider2",
    "snowspider_spike2",
    "snowspiderden2",
    "rock_ice_frost",
    "icepillar",
    "snowgoat",
    "snowgoatherd",
    "snowwarg",
    "snowperd",
    "snowdeciduoustrees",
    "rock_ice_frost_spawner",
    "snowwarg_spawner",
}
