Assets = {
    Asset("ANIM", "anim/oxygen_meter_player.zip"),
    Asset("ANIM", "anim/hunger_ghost.zip"),
    Asset("ANIM", "anim/squidunderwater.zip"),
    Asset("ANIM", "anim/sandstone_boulder.zip"),
    Asset("ANIM", "anim/vent.zip"),
    Asset("ANIM", "anim/fish_fillet.zip"),
    Asset("ANIM", "anim/commonfish.zip"),
    Asset("ANIM", "anim/sand.zip"),
    Asset("ANIM", "anim/pearl.zip"),
    Asset("ANIM", "anim/iron_ore.zip"),
    Asset("ANIM", "anim/lavastone.zip"),
    Asset("ANIM", "anim/clam.zip"),
    Asset("ANIM", "anim/sea_eel.zip"),
    Asset("ANIM", "anim/sunken_chest.zip"),
    Asset("ANIM", "anim/kelp.zip"),
    Asset("ANIM", "anim/wormplant.zip"),
    Asset("ANIM", "anim/decorative_shell.zip"),
    Asset("ANIM", "anim/coral_orange.zip"),
    Asset("ANIM", "anim/sponge.zip"),
    Asset("ANIM", "anim/fish_n_chips.zip"),
    Asset("ANIM", "anim/fish_gazpacho.zip"),
    Asset("ANIM", "anim/sponge_cake.zip"),
    Asset("ANIM", "anim/tuna_muffin.zip"),
    Asset("ANIM", "anim/sea_cucumber.zip"),
    Asset("ANIM", "anim/jelly_cap.zip"),
    Asset("ANIM", "anim/shrimp.zip"),
    Asset("ANIM", "anim/diving_suit_summer.zip"),
    Asset("ANIM", "anim/diving_suit_winter.zip"),
    Asset("ANIM", "anim/tentacle_sushi.zip"),
    Asset("ANIM", "anim/flower_sushi.zip"),
    Asset("ANIM", "anim/fish_sushi.zip"),
    Asset("ANIM", "anim/shrimp_tail.zip"),
    Asset("ANIM", "anim/jelly_lantern.zip"),
    Asset("ANIM", "anim/seagrass_chunk.zip"),
    Asset("ANIM", "anim/underwater_entrance.zip"),
    Asset("ANIM", "anim/underwater_exit.zip"),
    Asset("ANIM", "anim/coral_orange_ground.zip"),
    Asset("ANIM", "anim/coral_blue_ground.zip"),
    Asset("ANIM", "anim/coral_green_ground.zip"),
    Asset("ANIM", "anim/snorkel.zip"),
    Asset("ANIM", "anim/seajelly.zip"),
    Asset("ANIM", "anim/coral_cluster.zip"),
    Asset("ANIM", "anim/uw_flowers.zip"),
    Asset("ANIM", "anim/sea_petals.zip"),
    Asset("SOUNDPACKAGE", "sound/citd.fev"),
    Asset("SOUND", "sound/citd.fsb"),
}

----------------------------------------------------------------------------------------------------

-- Add minimap atlas
AddMinimapAtlas("images/minimap/iron_boulder.xml")

----------------------------------------------------------------------------------------------------
