local TechTree = require("techtree")
local wilson_health = 150


TUNING.IRON_LORD_TIME = 180

TUNING.ARMORSEASHELL = TUNING.DEFAULT_CHARACTER_HEALTH * 5
TUNING.ARMORSEASHELL_ABSORPTION = 0.75

TUNING.ARMOR_SNAKESKIN_FUEL = 480 * 8

TUNING.ARMORVORTEX = TUNING.DEFAULT_CHARACTER_HEALTH * 3
TUNING.ARMORVORTEXFUEL = TUNING.ARMORVORTEX / 45 * TUNING.LARGE_FUEL
TUNING.ARMORVORTEX_ABSORPTION = 1

TUNING.ARMORVOIDCLOAK = TUNING.ARMORVORTEX / 10 * 19
TUNING.ARMORVOIDCLOAK_FUEL = TUNING.ARMORVOIDCLOAK / 45 * TUNING.LARGE_FUEL
TUNING.ARMORVOIDCLOAK_ABSORPTION = TUNING.ARMORVORTEX_ABSORPTION

TUNING.ARMOROBSIDIAN = TUNING.DEFAULT_CHARACTER_HEALTH * 9

TUNING.ARMOR_WEEVOLE = TUNING.DEFAULT_CHARACTER_HEALTH * 6
TUNING.ARMOR_WEEVOLE_ABSORPTION = .65

TUNING.ARMOR_WINDBREAKER_FUEL = 4800

TUNING.WILBUR_HEALTH = 125
TUNING.WILBUR_SANITY = 150
TUNING.WILBUR_HUNGER = 175

TUNING.WOODLEGS_HEALTH = 150
TUNING.WOODLEGS_SANITY = 120
TUNING.WOODLEGS_HUNGER = 150

TUNING.WALANI_HEALTH = 120
TUNING.WALANI_SANITY = 200
TUNING.WALANI_HUNGER = 200

TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.WOODLEGS = { "woodlegshat", "boatcannon", "boards", "boards", "boards", "boards",
    "dubloon", "dubloon", "dubloon", "dubloon" }
TUNING.STARTING_ITEM_IMAGE_OVERRIDE["woodlegshat"] = {
    image = "woodlegshat.tex",
}
TUNING.STARTING_ITEM_IMAGE_OVERRIDE["boatcannon"] = {
    image = "boatcannon.tex",
}
TUNING.STARTING_ITEM_IMAGE_OVERRIDE["dubloon"] = {
    image = "dubloon.tex",
}


TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.WALANI = { "surfboard_item" }
TUNING.STARTING_ITEM_IMAGE_OVERRIDE["surfboard_item"] = {
    image = "surfboard_item.tex",
}

--glass---------------------------
----------------------------------
TUNING.SWP_SHARD_DMG = {
    BEAK = 51,
    SWORD = 50,
    SHADOW_MODIFIER_MINIMUM = 2,
    SHADOW_MODIFIER_MAXIMUM = 8,
    STRUCTURE_MODIFIER = 3,
    SWEEP_MODIFIER = .5,
}

-- 可以定义STRINGS.UI.CRAFTING.NEEDXXX在制作栏显示一些文本
TUNING.PROTOTYPER_TREES.OBSIDIAN_TWO = TechTree.Create({
    OBSIDIAN = 2,
})

TUNING.PROTOTYPER_TREES.CITY_ONE = TechTree.Create({
    CITY = 1,
})

TUNING.PROTOTYPER_TREES.HOME_TWO = TechTree.Create({
    HOME = 2,
})

TUNING.PROTOTYPER_TREES.GODDESS_TWO = TechTree.Create({
    GODDESS = 2,
})
TUNING.PROTOTYPER_TREES.GORGE_TWO = TechTree.Create({
    GORGE = 2,
})


TUNING.BOAT_LANTERN_LIGHTTIME = (60 + 120) * 2.6

TUNING.BOAT_TORCH_LIGHTTIME = 60 * 1.75

TUNING.COFFEE_SPEED_INCREASE = 5 / 6
TUNING.BUFF_COFFEE_DURATION = TUNING.TOTAL_DAY_TIME / 2
TUNING.BOUILLABAISSE_SPEED_MODIFIER = 1.5
TUNING.BUFF_BOUILLABAISSE_DURATION = TUNING.SEG_TIME

TUNING.SHARK_HAT_PERISHTIME = TUNING.EYEBRELLA_PERISHTIME

TUNING.GOGGLES_PERISHTIME = TUNING.TOTAL_DAY_TIME * 10
TUNING.GOGGLES_HEAT_PERISHTIME = TUNING.TOTAL_DAY_TIME * 2
TUNING.GOGGLES_ARMOR_ARMOR = wilson_health * 4 * 0.7
TUNING.GOGGLES_ARMOR_ABSORPTION = 0.85
TUNING.GOGGLES_SHOOT_USES = 10

TUNING.GOGGLES_HEAT =
{
    HOT =
    {
        BLOOM        = true,
        DESATURATION = 1.0,
        MULT_COLOUR  = { 0.0, 1.0, 0.5, 1.0 },
        ADD_COLOUR   = { 1.0, 0.1, 0.3, 1.0 },
    },
    COLD =
    {
        BLOOM        = false,
        DESATURATION = 0.7,
        MULT_COLOUR  = { 0.0, 0.0, 0.3, 1.0 },
        ADD_COLOUR   = { 0.1, 0.1, 0.5, 1.0 },
    },
    GROUND =
    {
        MULT_COLOUR = { 0.0, 0.1, 0.3, 1.0 },
        ADD_COLOUR  = { 0.1, 0.1, 0.5, 1.0 }
    },
    WAVES =
    {
        MULT_COLOUR = { 0.0, 0.0, 0.3, 1.0 },
        ADD_COLOUR  = { 0.1, 0.1, 0.6, 1.0 },
    },
    BLUR =
    {
        ENABLED = true,
        START_RADIUS = -5.0,
        STRENGTH = 0.16,
    }
}
