local TechTree = require("techtree")

TUNING.HAMROOM = {
    roomtype = {
        playerhouse_city_floor = "large",
        pig_palace_floor = "xlarge",
        vampirebatcave_floor = "cave",
        roc_cave_floor = "cave",
        pig_shop_florist_floor = "small",
        pig_palace_gallery_floor = "big", ----------这两个啥都不合适
        pig_palace_shop_floor = "medium",
    },


    roomcamera = {
        small = { pitch = 36, distance = 20, pos = -1 },
        medium = { pitch = 35, distance = 24, pos = -2 },
        big = { pitch = 35, distance = 27, pos = -1 },
        large = { pitch = 36, distance = 27, pos = -2.5 },
        cave = { pitch = 36, distance = 31, pos = 0 },
        xlarge = { pitch = 36, distance = 38, pos = -2 },
    },

    roomsize = {
        small = { back = 2.5, front = 9, side = 7.5 },
        medium = { back = 5, front = 8.5, side = 7.5 },
        big = { back = 5, front = 9.5, side = 9 },
        large = { back = 5, front = 8, side = 11.5 },
        cave = { back = 5, front = 13, side = 13 },
        xlarge = { back = 5.5, front = 13, side = 13 },
    },
}

TUNING.OINCS = {
    oinc = 1,
    oinc10 = 10,
    oinc100 = 100,
}

TUNING.TFWP_SPEAR_GUNG =
{
    USES = 200,
    DAMAGE = 40,
    SPELL_DAMAGE = 75,
    RECHARGE = 15,
    DECAY_PER_CAST = 200 * 0.05,
}

TUNING.TFWP_LAVA_HAMMER =
{
    USES = 250,
    DAMAGE = 35,
    SPELL_DAMAGE = 50,
    RECHARGE = 15,
    DECAY_PER_CAST = 250 * 0.05,
}

TUNING.TFWP_SPEAR_LANCE =
{
    USES = 150,
    DAMAGE = 45,
    SPELL_DAMAGE = 150,
    RECHARGE = 15,
    DECAY_PER_CAST = 100 * 0.05,
}

TUNING.TFWP_SUMMON_BOOK =
{
    USES = 60,
    DAMAGE = 20,
    RECHARGE = 60,
    DECAY_PER_CAST = 60 * 0.1,
}

TUNING.TFWP_CONTROL_BOOK =
{
    USES = 60,
    DAMAGE = 20,
    RECHARGE = 45,
    DECAY_PER_CAST = 60 * 0.1,
}

TUNING.TFWP_HEALING_STAFF =
{
    USES = 80,
    DAMAGE = 20,
    RECHARGE = 30,
    HEALTH_PER_SECOND = 3,
    SANITY_PER_SECOND = 1,
    DECAY_PER_CAST = 80 * 0.1,
}

TUNING.TFWP_INFERNAL_STAFF =
{
    USES = 80,
    DAMAGE = 25,
    RECHARGE = 20,
    SPELL_DAMAGE = 300,
    DECAY_PER_CAST = 80 * 0.05,
}

TUNING.TFWP_DRAGON_DART =
{
    USES = 30,
    DAMAGE = 20,
    RECHARGE = 5,
    SPELL_DAMAGE = 60,
    DECAY_PER_CAST = 1,
}

TUNING.TFWP_LAVA_DART =
{
    USES = 40,
    DAMAGE = 15,
    RECHARGE = 15,
    SPELL_DAMAGE = 15,
    DECAY_PER_CAST = 2,
}

TUNING.TFWP_HEAVY_SWORD =
{
    USES = 300,
    DAMAGE = 37,
    SPELL_DAMAGE = 90,
}

--Elemetal
TUNING.TFWP_ELEMENTAL =
{
    HEALTH = 50,
    DAMAGE = 5,
    RANGE = 15,
    ATTACK_PERIOD = 0.7,
}

--turtle----------------------
------------------------------
TUNING.SPIKY_TURTLE_TFC = {}
TUNING.SPIKY_TURTLE_TFC.HEALTH = 1200
TUNING.SPIKY_TURTLE_TFC.KEEPDIST = 30
TUNING.SPIKY_TURTLE_TFC.WALKSPEED = 3
TUNING.SPIKY_TURTLE_TFC.TARGET_DIST = 25
--melee
TUNING.SPIKY_TURTLE_TFC.DAMAGE = 45
TUNING.SPIKY_TURTLE_TFC.RANGE = 4
TUNING.SPIKY_TURTLE_TFC.ATTACK_PERIOD = 1.7
--slides
TUNING.SPIKY_TURTLE_TFC.SLIDEDAMAGE = 45
TUNING.SPIKY_TURTLE_TFC.SLIDE_RADIUS = 3
TUNING.SPIKY_TURTLE_TFC.SLIDES_ALLOWED = 5
--hider
TUNING.SPIKY_TURTLE_TFC.SHELL_REQ_DAMAGE = 350
TUNING.SPIKY_TURTLE_TFC.INSHELL_TIME = 5
TUNING.SPIKY_TURTLE_TFC.SHIELDED_DAMAGE_REDUCTION = 0.95

--scorpion------------------------
----------------------------------
TUNING.STRANGE_SCORPION_TFC = {}
TUNING.STRANGE_SCORPION_TFC.HEALTH = 1200
TUNING.STRANGE_SCORPION_TFC.RUNSPEED = 3
TUNING.STRANGE_SCORPION_TFC.TARGET_DIST = 25
TUNING.STRANGE_SCORPION_TFC.KEEPDIST = 30
--melee
TUNING.STRANGE_SCORPION_TFC.DAMAGE = 45
TUNING.STRANGE_SCORPION_TFC.RANGE = 4
TUNING.STRANGE_SCORPION_TFC.ATTACK_PERIOD = 1.5
--range
TUNING.STRANGE_SCORPION_TFC.RANGE_ATTACK_PERIOD = 10
TUNING.STRANGE_SCORPION_TFC.SPITRANGE = 20
TUNING.STRANGE_SCORPION_TFC.SPITDAMAGE = 5
--splash
TUNING.STRANGE_SCORPION_TFC.STICKY_SPIT = true
TUNING.STRANGE_SCORPION_TFC.SPLASHRADIUS = 3
TUNING.STRANGE_SCORPION_TFC.SPLASHDAMAGE = 40
--spread
TUNING.STRANGE_SCORPION_TFC.SPREAD_TARGETS = 3

--piggy---------------------------
----------------------------------
TUNING.HATTY_PIGGY_TFC = {}
TUNING.HATTY_PIGGY_TFC.HEALTH = 400
TUNING.HATTY_PIGGY_TFC.RUNSPEED = 10
TUNING.HATTY_PIGGY_TFC.TARGET_DIST = 25
TUNING.HATTY_PIGGY_TFC.KEEPDIST = 30
TUNING.HATTY_PIGGY_TFC.SHARE_DIST = 25
--melee
TUNING.HATTY_PIGGY_TFC.DAMAGE = 45
TUNING.HATTY_PIGGY_TFC.RANGE = 2
TUNING.HATTY_PIGGY_TFC.ATTACK_PERIOD = 1.5
--charge
TUNING.HATTY_PIGGY_TFC.CHARGE_RECHARGE = 5
TUNING.HATTY_PIGGY_TFC.DAMAGE = 45

--elemental-------------------------
------------------------------------
TUNING.FLAME_ELEMENTAL_TFC = {}
TUNING.FLAME_ELEMENTAL_TFC.HEALTH = 400
--attack
TUNING.FLAME_ELEMENTAL_TFC.DAMAGE = 7
TUNING.FLAME_ELEMENTAL_TFC.RANGE = 15
TUNING.FLAME_ELEMENTAL_TFC.ATTACK_PERIOD = 0.7
--blast
TUNING.FLAME_ELEMENTAL_TFC.BLAST_DAMAGE = 250
TUNING.FLAME_ELEMENTAL_TFC.BLAST_RADIUS = 5

--lizardmen-------------------------
------------------------------------
TUNING.LIZARDMAN_TFC = {}
TUNING.LIZARDMAN_TFC.TARGET_DIST = 12
TUNING.LIZARDMAN_TFC.KEEP_TARGET_DIST = 20
TUNING.LIZARDMAN_TFC.DAMAGE = 25
TUNING.LIZARDMAN_TFC.ATTACK_PERIOD = 2.5
TUNING.LIZARDMAN_TFC.SPEED = 6
TUNING.LIZARDMAN_TFC.HEALTH = 680
TUNING.LIZARDMAN_TFC.SHARE_TARGET_DIST = 20
TUNING.LIZARDMAN_TFC.ATTACK_RANGE = 4
TUNING.LIZARDMAN_TFC.DIST_ATTACK_RANGE = 16
TUNING.LIZARDMAN_TFC.TORNS_DAMAGE = 5
TUNING.LIZARDMAN_TFC.BANNER_RECHARGE = 15

--boarilla--------------------------
------------------------------------
TUNING.SPIKY_MONKEY_TFC = {}
TUNING.SPIKY_MONKEY_TFC.SPEED = 7.5
TUNING.SPIKY_MONKEY_TFC.HEALTH = 1200
TUNING.SPIKY_MONKEY_TFC.TARGET_DIST = 12
TUNING.SPIKY_MONKEY_TFC.KEEP_TARGET_DIST = 20
--combat
TUNING.SPIKY_MONKEY_TFC.DAMAGE = 65
TUNING.SPIKY_MONKEY_TFC.ATTACK_PERIOD = 2.5
TUNING.SPIKY_MONKEY_TFC.ATTACK_RANGE = 4
--shield
TUNING.SPIKY_MONKEY_TFC.SHELL_REQ_DAMAGE = 350
TUNING.SPIKY_MONKEY_TFC.INSHELL_TIME = 5
TUNING.SPIKY_MONKEY_TFC.SHIELDED_DAMAGE_REDUCTION = 0.95
--slam
TUNING.SPIKY_MONKEY_TFC.SLAM_RECHARGE = 5
TUNING.SPIKY_MONKEY_TFC.SLAM_RADIUS = 5
TUNING.SPIKY_MONKEY_TFC.SLAM_DAMAGE = 100

TUNING.OBSIDIAN_TOOL_MAXHEAT = 60


TUNING.ADULT_FLYTRAP_HEALTH = 400
TUNING.ADULT_FLYTRAP_DAMAGE = 30
TUNING.ADULT_FLYTRAP_ATTACK_PERIOD = 5
TUNING.ADULT_FLYTRAP_ATTACK_DIST = 4
TUNING.ADULT_FLYTRAP_STOPATTACK_DIST = 6
TUNING.ADULT_FLYTRAP_GROW_TIME = 480 * 2

TUNING.ANCIENT_HERALD_HEALTH = 8000 * TUNING.tropical.bosslife
TUNING.ANCIENT_HERALD_DAMAGE = 50

TUNING.ANCIENT_HULK_HEALTH = 8000 * TUNING.tropical.bosslife
TUNING.ANCIENT_HULK_DAMAGE = 200
TUNING.ANCIENT_HULK_MINE_DAMAGE = 100
TUNING.ANCIENT_HULK_MELEE_RANGE = 5.5
TUNING.ANCIENT_HULK_ATTACK_RANGE = 5.5

TUNING.ANTQUEEN_HEALTH = 16000 * TUNING.tropical.bosslife

TUNING.ARMORCACTUS = TUNING.DEFAULT_CHARACTER_HEALTH * 3
TUNING.ARMORCACTUS_ABSORPTION = .8

TUNING.ARMORLIMESTONE = 150 * 5.5
TUNING.ARMORLIMESTONE_ABSORPTION = .70
TUNING.ARMORLIMESTONE_SLOW = 0.90

TUNING.ARMORMETAL = 150 * 8
TUNING.ARMORMETAL_ABSORPTION = .85
TUNING.ARMORMETAL_SLOW = 0.90

TUNING.ARMORSEASHELL = TUNING.DEFAULT_CHARACTER_HEALTH * 5
TUNING.ARMORSEASHELL_ABSORPTION = 0.75

TUNING.ARMOR_SNAKESKIN_FUEL = 480 * 8

TUNING.ARMORVORTEX = TUNING.DEFAULT_CHARACTER_HEALTH * 3
TUNING.ARMORVORTEXFUEL = TUNING.ARMORVORTEX / 45 * TUNING.LARGE_FUEL
TUNING.ARMORVORTEX_ABSORPTION = 1

TUNING.ARMORVOIDCLOAK = TUNING.ARMORVORTEX / 10 * 19
TUNING.ARMORVOIDCLOAK_FUEL = TUNING.ARMORVOIDCLOAK / 45 * TUNING.LARGE_FUEL
TUNING.ARMORVOIDCLOAK_ABSORPTION = TUNING.ARMORVORTEX_ABSORPTION

TUNING.ARMOROBSIDIAN = TUNING.DEFAULT_CHARACTER_HEALTH * 9

TUNING.ARMOR_WEEVOLE = TUNING.DEFAULT_CHARACTER_HEALTH * 6
TUNING.ARMOR_WEEVOLE_ABSORPTION = .65

TUNING.ARMOR_WINDBREAKER_FUEL = 4800

TUNING.WILBUR_HEALTH = 125
TUNING.WILBUR_SANITY = 150
TUNING.WILBUR_HUNGER = 175
TUNING.WOODLEGS_HEALTH = 150
TUNING.WOODLEGS_SANITY = 120
TUNING.WOODLEGS_HUNGER = 150
TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.WOODLEGS = { "woodlegshat", "boatcannon", "boards", "boards", "boards", "boards",
    "dubloon", "dubloon", "dubloon", "dubloon" }
TUNING.STARTING_ITEM_IMAGE_OVERRIDE["woodlegshat"] = {
    image = "woodlegshat.tex",
}
TUNING.STARTING_ITEM_IMAGE_OVERRIDE["boatcannon"] = {
    image = "boatcannon.tex",
}
TUNING.STARTING_ITEM_IMAGE_OVERRIDE["dubloon"] = {
    image = "dubloon.tex",
}
TUNING.WALANI_HEALTH = 120
TUNING.WALANI_SANITY = 200
TUNING.WALANI_HUNGER = 200

TUNING.GAMEMODE_STARTING_ITEMS.DEFAULT.WALANI = { "surfboard_item" }
TUNING.STARTING_ITEM_IMAGE_OVERRIDE["surfboard_item"] = {
    image = "surfboard_item.tex",
}

--glass---------------------------
----------------------------------
TUNING.SWP_SHARD_DMG = {
    BEAK = 34,
    SWORD = 50,
    SHADOW_MODIFIER_MINIMUM = 2,
    SHADOW_MODIFIER_MAXIMUM = 8,
    STRUCTURE_MODIFIER = 5,
}

local dm = 1.5
TUNING.FORGE_ITEM_PACK = {
    GOLEM = { HEALTH = 1, RUNSPEED = 0, DAMAGE = 25, HIT_RANGE = 9, ATTACK_PERIOD = 2, LIFE_TIME = 50 },
    TFWP_LAVA_DART = { DAMAGE = 20 * dm, COOLDOWN = 18, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, DISABLE_RECIPE = false },
    TFWP_LAVA_HAMMER = { DAMAGE = 20 * dm, ALT_DAMAGE = 30 * dm / TUNING.ELECTRIC_DAMAGE_MULT, ALT_RADIUS = 4.1, COOLDOWN = 18, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, WORKABLE_DMG = 4, DISABLE_RECIPE = false },
    RILEDLUCY = { DAMAGE = 20 * dm, ALT_DAMAGE = 30 * dm, WORKABLE_DMG = 4, DISABLE_RECIPE = false },
    TFWP_SPEAR_GUNG = { DAMAGE = 25 * dm, ALT_DAMAGE = 25 * dm, ALT_DIST = 6.5, ALT_WIDTH = 3.25, COOLDOWN = 12, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, WORKABLE_DMG = 4, DISABLE_RECIPE = false },
    TFWP_HEALING_STAFF = { DAMAGE = 10 * dm, COOLDOWN = 24, DURATION = 10, HEAL_RATE = 6, RANGE = 4.1, SCALE_RNG = { 30, 40 }, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, DISABLE_RECIPE = false },
    TFWP_DRAGON_DART = { DAMAGE = 25 * dm, ALT_DAMAGE = 50 * dm, COOLDOWN = 18, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, DISABLE_RECIPE = false },
    TFWP_INFERNAL_STAFF = { DAMAGE = 25 * dm, ALT_DAMAGE = { base = 200 * dm, center_mult = 0.25 }, ALT_RADIUS = 4.1, COOLDOWN = 24, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, WORKABLE_DMG = 8, DISABLE_RECIPE = false },
    TFWP_SPEAR_LANCE = { DAMAGE = 30 * dm, ALT_DAMAGE = 75 * dm, ALT_RANGE = 16, ALT_RADIUS = 2.05, COOLDOWN = 12, DURABILITY = { AMOUNT = 0, CONSUMPTION_SPECIAL = 0.5 }, WORKABLE_DMG = 6, DISABLE_RECIPE = false },
    TFWP_CONTROL_BOOK = { DAMAGE = 15 * dm, COOLDOWN = 18, DURATION = 10, ALT_RADIUS = 4.1, DURABILITY = { AMOUNT = 0, CONSUMPTION_SPECIAL = 0.5 }, DISABLE_RECIPE = false },
    TFWP_SUMMON_BOOK = { DAMAGE = 15 * dm, COOLDOWN = 18, DURATION = 10, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, DISABLE_RECIPE = false },
    TFWP_FIRE_BOMB = { DAMAGE = 15 * dm, ALT_DAMAGE = 75 * dm, PROC_DAMAGE = 100 * dm, COOLDOWN = 6, ALT_RANGE = 8, HORIZONTAL_SPEED = 20, GRAVITY = -30, CHARGE_HITS_1 = 7, CHARGE_HITS_2 = 10, MAXIMUM_CHARGE_HITS = 13, CHARGE_DECAY_TIME = 5, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, WORKABLE_DMG = 4, DISABLE_RECIPE = false },
    TFWP_HEAVY_SWORD = { DAMAGE = 30 * dm, HELMSPLIT_DAMAGE = 100 * dm, PARRY_DURATION = 5, COOLDOWN = 12, DURABILITY = { AMOUNT = 0, CONSUMPTION_NORMAL = 1, CONSUMPTION_SPECIAL = 0.5 }, DISABLE_RECIPE = false },

    RET_DATA = {
        fossil = { "aoecctarget", 2 },
        elemental = { "aoesummontarget", 1 },
        hammer = { "aoehostiletarget", 0.9 },
        tfwp_healing_staff = { "aoefriendlytarget", 0.9 },
        fireballstaff = { "aoehostiletarget", 0.7 },
        tfwp_spear_lance = { "aoesmallhostiletarget", 1 },
        tfwp_fire_bomb = { "aoesmallhostiletarget", 1 },
        tfwp_heavy_sword = { "aoehostiletarget", 0.9 }
    }
}

TUNING.FORGE_ITEM_PACK.GOLEM.DAMAGE = 25 * dm
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_DART.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_DART.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_DART.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_DART.DAMAGE = 20 * dm
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_HAMMER.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_HAMMER.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_HAMMER.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_HAMMER.COOLDOWN = 18
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_HAMMER.DAMAGE = 20 * dm
TUNING.FORGE_ITEM_PACK.TFWP_LAVA_HAMMER.ALT_DAMAGE = 30 * dm / TUNING.ELECTRIC_DAMAGE_MULT;
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_GUNG.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_GUNG.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_GUNG.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_GUNG.COOLDOWN = 12
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_GUNG.DAMAGE = 25 * dm
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_GUNG.ALT_DAMAGE = 25 * dm
TUNING.FORGE_ITEM_PACK.TFWP_HEALING_STAFF.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_HEALING_STAFF.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_HEALING_STAFF.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_HEALING_STAFF.COOLDOWN = 24
TUNING.FORGE_ITEM_PACK.TFWP_HEALING_STAFF.DURATION = 10
TUNING.FORGE_ITEM_PACK.TFWP_HEALING_STAFF.HEAL_RATE = 6
TUNING.FORGE_ITEM_PACK.TFWP_HEALING_STAFF.DAMAGE = 10 * dm
TUNING.FORGE_ITEM_PACK.TFWP_DRAGON_DART.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_DRAGON_DART.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_DRAGON_DART.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_DRAGON_DART.COOLDOWN = 18
TUNING.FORGE_ITEM_PACK.TFWP_DRAGON_DART.DAMAGE = 25 * dm
TUNING.FORGE_ITEM_PACK.TFWP_DRAGON_DART.ALT_DAMAGE = 50 * dm
TUNING.FORGE_ITEM_PACK.TFWP_INFERNAL_STAFF.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_INFERNAL_STAFF.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_INFERNAL_STAFF.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_INFERNAL_STAFF.COOLDOWN = 24
TUNING.FORGE_ITEM_PACK.TFWP_INFERNAL_STAFF.DAMAGE = 25 * dm
TUNING.FORGE_ITEM_PACK.TFWP_INFERNAL_STAFF.ALT_DAMAGE.base = 200 * dm
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_LANCE.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_LANCE.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_LANCE.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_LANCE.COOLDOWN = 12
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_LANCE.DAMAGE = 30 * dm
TUNING.FORGE_ITEM_PACK.TFWP_SPEAR_LANCE.ALT_DAMAGE = 75 * dm
TUNING.FORGE_ITEM_PACK.TFWP_CONTROL_BOOK.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_CONTROL_BOOK.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_CONTROL_BOOK.COOLDOWN = 18
TUNING.FORGE_ITEM_PACK.TFWP_CONTROL_BOOK.DAMAGE = 15 * dm
TUNING.FORGE_ITEM_PACK.TFWP_SUMMON_BOOK.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_SUMMON_BOOK.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_SUMMON_BOOK.COOLDOWN = 18
TUNING.FORGE_ITEM_PACK.TFWP_SUMMON_BOOK.DAMAGE = 15 * dm
TUNING.FORGE_ITEM_PACK.TFWP_FIRE_BOMB.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_FIRE_BOMB.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_FIRE_BOMB.COOLDOWN = 5
TUNING.FORGE_ITEM_PACK.TFWP_FIRE_BOMB.DAMAGE = 15 * dm
TUNING.FORGE_ITEM_PACK.TFWP_FIRE_BOMB.ALT_DAMAGE = 75 * dm
TUNING.FORGE_ITEM_PACK.TFWP_FIRE_BOMB.PROC_DAMAGE = 100 * dm
TUNING.FORGE_ITEM_PACK.TFWP_HEAVY_SWORD.DURABILITY.AMOUNT = 800
TUNING.FORGE_ITEM_PACK.TFWP_HEAVY_SWORD.DURABILITY.CONSUMPTION_NORMAL = 1
TUNING.FORGE_ITEM_PACK.TFWP_HEAVY_SWORD.DURABILITY.CONSUMPTION_SPECIAL = 0.5
TUNING.FORGE_ITEM_PACK.TFWP_HEAVY_SWORD.COOLDOWN = 12
TUNING.FORGE_ITEM_PACK.TFWP_HEAVY_SWORD.DAMAGE = 30 * dm
TUNING.FORGE_ITEM_PACK.TFWP_HEAVY_SWORD.HELMSPLIT_DAMAGE = 100 * dm

TUNING.PROTOTYPER_TREES.OBSIDIAN_ONE = TechTree.Create({
    OBSIDIAN = 1,
})
TUNING.PROTOTYPER_TREES.OBSIDIAN_TWO = TechTree.Create({
    OBSIDIAN = 2,
})

TUNING.PROTOTYPER_TREES.CITY_ONE = TechTree.Create({
    CITY = 1,
})
TUNING.PROTOTYPER_TREES.CITY_TWO = TechTree.Create({
    CITY = 2,
})

TUNING.PROTOTYPER_TREES.HOME_ONE = TechTree.Create({
    HOME = 1,
})
TUNING.PROTOTYPER_TREES.HOME_TWO = TechTree.Create({
    HOME = 2,
})

TUNING.PROTOTYPER_TREES.GODDESS_ONE = TechTree.Create({
    GODDESS = 1,
})
TUNING.PROTOTYPER_TREES.GODDESS_TWO = TechTree.Create({
    GODDESS = 2,
})
TUNING.PROTOTYPER_TREES.GORGE_ONE = TechTree.Create({
    GORGE = 1,
})
TUNING.PROTOTYPER_TREES.GORGE_TWO = TechTree.Create({
    GORGE = 2,
})


TUNING.BOAT_LANTERN_LIGHTTIME = (60 + 120) * 2.6

TUNING.BOAT_TORCH_LIGHTTIME = 60 * 1.75

TUNING.COFFEE_SPEED_INCREASE = 5 / 6
TUNING.BUFF_COFFEE_DURATION = TUNING.TOTAL_DAY_TIME / 2
TUNING.BOUILLABAISSE_SPEED_MODIFIER = 1.5
TUNING.BUFF_BOUILLABAISSE_DURATION = TUNING.SEG_TIME

TUNING.SHARK_HAT_PERISHTIME = TUNING.EYEBRELLA_PERISHTIME

TUNING.SPOILED_FISH_LARGE_NUTRIENTS = { 24, 0, 0 }

TUNING.MYSTERYMEAT_NUTRIENTS = { 24, 24, 24 }

TUNING.JELLYFISH_WEIGHTS = {
    min = 61.55,
    max = 90.11,
}
TUNING.RAINBOWJELLYFISH_WEIGHTS = {
    min = 69.36,
    max = 118.21,
}
