require("map/lockandkey")
-- local LOCKS = GLOBAL.LOCKS
-- local KEYS = GLOBAL.KEYS
-- local LOCKS_KEYS = GLOBAL.LOCKS_KEYS

-- local dimlock = #LOCKS
-- local dimkey = #KEYS

--------------------------------------
-------adding new keys and locks------
--------------------------------------

ARRAY_NEW =
{

    "HAM_CAVE",
    "HAM_ANT",
    "HAM_CAVE2",
    "HAM_MAZE",

    "PLAIN",
    "RAINFOREST",
    "DEEPRAINFOREST",
    "EDGE",
    "PAINTED",
    "CITY_1",
    "CITY_2",

    "HAM_BLANK",
    "HAM_BLANK1",
    "HAM_BLANK2",
    "SNAKE",

    "DEEPRAINFOREST_CITY2",
    "DEEPRAINFOREST_SNAKE",
    "LOST_JUNGLE",

    "JUNGLE_DEPTH_1",
    "JUNGLE_DEPTH_2",
    "JUNGLE_DEPTH_3",

    "CIVILIZATION_1",
    "CIVILIZATION_2",

    "LAND_DIVIDE_1",
    "LAND_DIVIDE_2",
    "LAND_DIVIDE_3",
    "LAND_DIVIDE_4",
    "LAND_DIVIDE_5", ------

    "OTHER_JUNGLE_DEPTH_1",
    "OTHER_JUNGLE_DEPTH_2",
    "LOST_JUNGLE_DEPTH_2",

    "ISLAND_1",
    "ISLAND_2",
    "ISLAND_3",
    "ISLAND_4",
    "ISLAND_5",

    "PINACLE",

    "OTHER_CIVILIZATION_1",
    "OTHER_CIVILIZATION_2",

    "WILD_JUNGLE_DEPTH_1",
    "WILD_JUNGLE_DEPTH_2",

    "ISLAND1",
    "ISLAND2",
    "ISLAND3",
    "ISLAND4",
    "ISLAND5",
    "ISLAND6",
    "ISLAND7",
    "ISLAND8",
    "ISLAND9",
    "ISLAND10",
    "ISLAND11",

    "VOLCANO_ENTRANCE",
    "VOLCANO",
    "VOLCANO_INNER",
}


local function AddSimpleKeyLock(name)
    table.insert(KEYS_ARRAY, name)
    KEYS[name] = #KEYS_ARRAY
    table.insert(LOCKS_ARRAY, name)
    LOCKS[name] = #KEYS_ARRAY
    LOCKS_KEYS[LOCKS[name]] = { KEYS[name] }
end


for i, v in ipairs(ARRAY_NEW) do
    AddSimpleKeyLock(v)
end


-- for i, v in ipairs(LOCKS_ARRAY_NEW) do
--     assert(LOCKS[v] == nil, "Lock " .. v .. " is defined twice!")
--     LOCKS[v] = i + dimlock
-- end


-- KEYS_ARRAY_NEW = LOCKS_ARRAY_NEW

-- for i, v in ipairs(KEYS_ARRAY_NEW) do
--     assert(KEYS[v] == nil, "Key " .. v .. " is defined twice!")
--     KEYS[v] = i + dimkey
-- end



-- LOCKS_KEYS[LOCKS.JUNGLE_DEPTH_1] = { KEYS.JUNGLE_DEPTH_1 }
-- LOCKS_KEYS[LOCKS.JUNGLE_DEPTH_2] = { KEYS.JUNGLE_DEPTH_2 }
-- LOCKS_KEYS[LOCKS.JUNGLE_DEPTH_3] = { KEYS.JUNGLE_DEPTH_3 }
-- LOCKS_KEYS[LOCKS.CIVILIZATION_1] = { KEYS.CIVILIZATION_1 }
-- LOCKS_KEYS[LOCKS.LAND_DIVIDE_1] = { KEYS.LAND_DIVIDE_1 }
-- LOCKS_KEYS[LOCKS.LAND_DIVIDE_2] = { KEYS.LAND_DIVIDE_2 }
-- LOCKS_KEYS[LOCKS.LAND_DIVIDE_3] = { KEYS.LAND_DIVIDE_3 }
-- LOCKS_KEYS[LOCKS.OTHER_JUNGLE_DEPTH_1] = { KEYS.OTHER_JUNGLE_DEPTH_1 }
-- LOCKS_KEYS[LOCKS.OTHER_JUNGLE_DEPTH_2] = { KEYS.OTHER_JUNGLE_DEPTH_2 }
-- LOCKS_KEYS[LOCKS.LOST_JUNGLE_DEPTH_2] = { KEYS.LOST_JUNGLE_DEPTH_2 }
-- LOCKS_KEYS[LOCKS.ISLAND_1] = { KEYS.ISLAND_1 }
-- LOCKS_KEYS[LOCKS.ISLAND_2] = { KEYS.ISLAND_2 }
-- LOCKS_KEYS[LOCKS.ISLAND_3] = { KEYS.ISLAND_3 }
-- LOCKS_KEYS[LOCKS.ISLAND_4] = { KEYS.ISLAND_4 }
-- LOCKS_KEYS[LOCKS.PINACLE] = { KEYS.PINACLE }
-- LOCKS_KEYS[LOCKS.CIVILIZATION_2] = { KEYS.CIVILIZATION_2 }
-- LOCKS_KEYS[LOCKS.LAND_DIVIDE_4] = { KEYS.LAND_DIVIDE_4 }
-- LOCKS_KEYS[LOCKS.OTHER_CIVILIZATION_1] = { KEYS.OTHER_CIVILIZATION_1 }
-- LOCKS_KEYS[LOCKS.OTHER_CIVILIZATION_2] = { KEYS.OTHER_CIVILIZATION_2 }
-- LOCKS_KEYS[LOCKS.WILD_JUNGLE_DEPTH_1] = { KEYS.WILD_JUNGLE_DEPTH_1 }
-- LOCKS_KEYS[LOCKS.WILD_JUNGLE_DEPTH_2] = { KEYS.WILD_JUNGLE_DEPTH_2 }
-- LOCKS_KEYS[LOCKS.ISLAND_5] = { KEYS.ISLAND_5 }
-- LOCKS_KEYS[LOCKS.LAND_DIVIDE_5] = { KEYS.LAND_DIVIDE_5 }
-- LOCKS_KEYS[LOCKS.ISLAND1] = { KEYS.ISLAND1 }
-- LOCKS_KEYS[LOCKS.ISLAND2] = { KEYS.ISLAND2 }
-- LOCKS_KEYS[LOCKS.ISLAND3] = { KEYS.ISLAND3 }
-- LOCKS_KEYS[LOCKS.ISLAND4] = { KEYS.ISLAND4 }
-- LOCKS_KEYS[LOCKS.ISLAND5] = { KEYS.ISLAND5 }
-- LOCKS_KEYS[LOCKS.ISLAND6] = { KEYS.ISLAND6 }
-- LOCKS_KEYS[LOCKS.ISLAND7] = { KEYS.ISLAND7 }
-- LOCKS_KEYS[LOCKS.ISLAND8] = { KEYS.ISLAND8 }
-- LOCKS_KEYS[LOCKS.ISLAND9] = { KEYS.ISLAND9 }
-- LOCKS_KEYS[LOCKS.ISLAND10] = { KEYS.ISLAND10 }
-- LOCKS_KEYS[LOCKS.ISLAND11] = { KEYS.ISLAND11 }
