TUNING.ROOM_TINY_WIDTH   = 15
TUNING.ROOM_TINY_DEPTH   = 10

TUNING.ROOM_SMALL_WIDTH  = 18
TUNING.ROOM_SMALL_DEPTH  = 12

TUNING.ROOM_MEDIUM_WIDTH = 24
TUNING.ROOM_MEDIUM_DEPTH = 16

TUNING.ROOM_LARGE_WIDTH  = 26
TUNING.ROOM_LARGE_DEPTH  = 18
