AddRoom("SandyBottom", {
    colour = { r = 0, g = 0, b = 0, a = 0 },
    value = WORLD_TILES.UNDERWATER_SANDY,
    tags = { "RoadPoison" },
    contents = {
        distributepercent = 0.3,
        distributeprefabs = {
            seagrass = 0.35,
            sandstone_boulder = 0.01,
            bubble_vent = 0.03,
            kelpunderwater = 0.2,
            squidunderwater = 0.001,
            flower_sea = 0.1,
            decorative_shell = 0.05,
            wormplant = 0.1,
            sea_eel = 0.01,
            clam = 0.06,
            sponge = 0.25,
            sea_cucumber = 0.1,
            commonfish = 0.1,
            shrimp = 0.2,
            reeflight_small = 0.2,
            reeflight_tiny = 0.2,
            uw_flowers = 0.1,
        },
    },
})
AddRoom("SandyBottomCoralPatch", {
    colour = { r = 0, g = 0, b = 0, a = 0 },
    value = WORLD_TILES.UNDERWATER_SANDY,
    tags = { "RoadPoison" },
    contents = {
        countprefabs = {
            geothermal_vent = function() return (math.random(2) - 1) end,
        },

        distributepercent = 0.3,
        distributeprefabs = {
            seagrass = 0.01,
            sandstone_boulder = 0.1,
            uw_coral = 0.25,
            uw_coral_blue = 0.25,
            uw_coral_green = 0.25,
            reef_jellyfish = 0.1,
            bubble_vent = 0.03,
            kelpunderwater = 0.2,
            squidunderwater = 0.001,
            flower_sea = 0.1,
            decorative_shell = 0.2,
            wormplant = 0.1,
            clam = 0.06,
            sponge = 0.25,
            sea_cucumber = 0.3,
            commonfish = 0.1,
            shrimp = 0.1,
            reeflight_small = 0.2,
            reeflight_tiny = 0.2,
            uw_flowers = 0.1,
        },
    },
})

AddRoom("SandyBottomTreasureTrove", {
    colour = { r = 0, g = 0, b = 0, a = 0 },
    value = WORLD_TILES.UNDERWATER_SANDY,
    tags = { "RoadPoison" },
    contents = {
        countprefabs = {
            geothermal_vent = function() return (math.random(2) - 1) end,
            sunkenchest_spawner = function() return (math.random(2) - 1) end,
        },

        distributepercent = 0.3,
        distributeprefabs = {
            seagrass = 0.35,
            sandstone_boulder = 0.01,
            uw_coral = 0.4,
            uw_coral_blue = 0.3,
            uw_coral_green = 0.3,
            --			seatentacle = 0.01,
            rotting_trunk = 0.2,
            bubble_vent = 0.03,
            kelpunderwater = 0.5,
            squidunderwater = 0.001,
            flower_sea = 0.1,
            decorative_shell = 0.05,
            wormplant = 0.1,
            sea_eel = 0.2,
            clam = 0.06,
            sponge = 0.25,
            sea_cucumber = 0.1,
            commonfish = 0.1,
            shrimp = 0.1,
            reeflight_small = 0.2,
            reeflight_tiny = 0.2,
            uw_flowers = 0.1,
        },
    },
})

AddRoom("bg_SandyBottom", {
    colour = { r = 0, g = 0, b = 0, a = 0 },
    value = WORLD_TILES.UNDERWATER_SANDY,
    tags = { "RoadPoison" },
    contents = {
        distributepercent = 0.25,
        distributeprefabs = {
            seagrass = 0.15,
            uw_coral = 0.02,
            uw_coral_blue = 0.03,
            uw_coral_green = 0.03,
            kelpunderwater = 0.01,
            commonfish = 0.1,
            shrimp = 0.1,
            reeflight_small = 0.2,
            reeflight_tiny = 0.2,
            uw_flowers = 0.1,
        },
    },
})
