AddRoom("TidalZoneEntrance", {
    colour = { r = 0, g = 0, b = 0, a = 0 },
    value = WORLD_TILES.UNDERWATER_SANDY,
    tags = { "RoadPoison" },
    contents = {
        distributepercent = 0.7,
        distributeprefabs = {
            seagrass = 0.05,
            sandstone = 0.35,
            uw_coral = 0.01,
            uw_coral_blue = 0.01,
            uw_coral_green = 0.01,
            cut_orange_coral = 0.1,
            tidal_node = 5,
            sponge = 0.01,
            bubble_vent = 0.03,
            commonfish = 0.05,
            shrimp = 0.1,
            reeflight_small = 0.2,
            reeflight_tiny = 0.2,
        },
    },
})
AddRoom("TidalZone", {
    colour = { r = 0, g = 0, b = 0, a = 0 },
    value = WORLD_TILES.UNDERWATER_SANDY,
    tags = { "RoadPoison" },
    contents = {
        distributepercent = 0.7,
        distributeprefabs = {
            seagrass = 0.25,
            sandstone = 0.45,
            uw_coral = 0.04,
            uw_coral_blue = 0.04,
            uw_coral_green = 0.04,
            cut_orange_coral = 0.3,
            tidal_node = 5,
            squidunderwater = 0.008,
            sponge = 0.03,
            bubble_vent = 0.03,
            commonfish = 0.05,
            shrimp = 0.1,
            reeflight_small = 0.2,
            reeflight_tiny = 0.2,
        },
    },
})
AddRoom("bg_TidalZone", {
    colour = { r = 0, g = 0, b = 0, a = 0 },
    value = WORLD_TILES.UNDERWATER_SANDY,
    tags = { "RoadPoison" },
    contents = {
        distributepercent = 0.9,
        distributeprefabs = {
            seagrass = 0.25,
            sandstone = 0.45,
            uw_coral = 0.1,
            uw_coral_blue = 0.1,
            uw_coral_green = 0.1,
            cut_orange_coral = 0.3,
            tidal_node = 5,
            commonfish = 0.05,
            rainbowjellyfish_underwater = 0.01,
            shrimp = 0.1,
            reeflight_small = 0.2,
            reeflight_tiny = 0.2,
        },
    },
})
