local TechTree = require("techtree")
TUNING.PROTOTYPER_TREES.QUAGMIRE_TRADER_MERM = TechTree.Create({
    QUAGMIRE_TRADER_MERM = 1,
})
TUNING.PROTOTYPER_TREES.QUAGMIRE_TRADER_MERM2 = TechTree.Create({
    QUAGMIRE_TRADER_MERM2 = 1,
})
TUNING.PROTOTYPER_TREES.QUAGMIRE_GOATMUM = TechTree.Create({
    QUAGMIRE_GOATMUM = 1,
})
TUNING.PROTOTYPER_TREES.QUAGMIRE_SWAMPIGELDER = TechTree.Create({
    QUAGMIRE_SWAMPIGELDER = 1,
})
TUNING.PROTOTYPER_TREES.QUAGMIRE_GOATKID = TechTree.Create({
    QUAGMIRE_GOATKID = 1,
})
