PrefabFiles = {
    "goldbishop",
    "goldentomb",
    "goldmonkey",
    "goldbishop",
    "goldobi",
    "tikihead",
    "teepee",
    "tikimask",
    "tikifire",
    "wanawanatiki",
    "summerwalrus",
    "summerigloo",
    "octoatt",
    "octopus",
    "octohouse",
}
