modimport "modmain/hamlet/map/tasks/island1"
modimport "modmain/hamlet/map/tasks/island2"
modimport "modmain/hamlet/map/tasks/island3"
modimport "modmain/hamlet/map/tasks/island4"
modimport "modmain/hamlet/map/tasks/island5"
