table.insert(PrefabFiles, "quagmire_mealingstone")
table.insert(PrefabFiles, "quagmire_flour")
table.insert(PrefabFiles, "quagmire_foods")
table.insert(PrefabFiles, "quagmire_goatmilk")
table.insert(PrefabFiles, "quagmire_sap")
table.insert(PrefabFiles, "quagmire_syrup")

table.insert(PrefabFiles, "quagmire_casseroledish")
table.insert(PrefabFiles, "quagmire_crates")
table.insert(PrefabFiles, "quagmire_grill")
table.insert(PrefabFiles, "quagmire_oven")
table.insert(PrefabFiles, "quagmire_plates")
table.insert(PrefabFiles, "quagmire_pot")
table.insert(PrefabFiles, "quagmire_pot_hanger")
table.insert(PrefabFiles, "quagmire_salt_rack")
table.insert(PrefabFiles, "quagmire_sapbucket")
table.insert(PrefabFiles, "quagmire_slaughtertool")
table.insert(PrefabFiles, "quagmire_altar")
table.insert(PrefabFiles, "quagmire_seedpackets")

table.insert(PrefabFiles, "quagmire_sugarwoodtree")
table.insert(PrefabFiles, "quagmire_sugarwood_sapling")

table.insert(PrefabFiles, "quagmire_goatmum")
table.insert(PrefabFiles, "quagmire_swampigelder")

table.insert(PrefabFiles, "quagmire_oldstructures")
table.insert(PrefabFiles, "quagmire_lamp_post")
table.insert(PrefabFiles, "quagmire_altar_statue")
table.insert(PrefabFiles, "quagmire_portal")
