table.insert(Assets, Asset("IMAGE", "levels/textures/noise_windy.tex"))
table.insert(Assets, Asset("IMAGE", "levels/textures/mini_noise_windy.tex"))
table.insert(Assets, Asset("IMAGE", "levels/tiles/windy.tex"))
table.insert(Assets, Asset("FILE", "levels/tiles/windy.xml"))
table.insert(Assets, Asset("IMAGE", "images/map_icons/goddess_statue.tex"))
table.insert(Assets, Asset("ATLAS", "images/map_icons/goddess_statue.xml"))
table.insert(Assets, Asset("IMAGE", "images/map_icons/goddess_statue2.tex"))
table.insert(Assets, Asset("ATLAS", "images/map_icons/goddess_statue2.xml"))
table.insert(Assets, Asset("IMAGE", "images/map_icons/goddess_statue3.tex"))
table.insert(Assets, Asset("ATLAS", "images/map_icons/goddess_statue3.xml"))
table.insert(Assets, Asset("IMAGE", "images/map_icons/goddess_fountain.tex"))
table.insert(Assets, Asset("ATLAS", "images/map_icons/goddess_fountain.xml"))
table.insert(Assets, Asset("IMAGE", "images/map_icons/goddess_shrine.tex"))
table.insert(Assets, Asset("ATLAS", "images/map_icons/goddess_shrine.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/windyfan1.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/windyfan1.xml"))
table.insert(Assets, Asset("ANIM", "anim/windyfan.zip"))
table.insert(Assets, Asset("ANIM", "anim/swap_windyfan.zip"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/peach.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/peach.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/forbidden_fruit.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/forbidden_fruit.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/goddess_flute.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/goddess_flute.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/goddess_staff.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/goddess_staff.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/peachy_poop.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/peachy_poop.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/goddess_butterfly.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/goddess_butterfly.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/cutgreengrass.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/cutgreengrass.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/magicpowder.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/magicpowder.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/goddess_figure.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/goddess_figure.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/goddess_tori.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/goddess_tori.xml"))
table.insert(Assets, Asset("IMAGE", "images/map_icons/goddess_gate.tex"))
table.insert(Assets, Asset("ATLAS", "images/map_icons/goddess_gate.xml"))
table.insert(Assets, Asset("IMAGE", "images/map_icons/peach.tex"))
table.insert(Assets, Asset("ATLAS", "images/map_icons/peach.xml"))
table.insert(Assets, Asset("ANIM", "anim/goddess_bird_build.zip"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/goddess_bird.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/goddess_bird.tex"))
table.insert(Assets, Asset("ANIM", "anim/goddess_feather.zip"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/goddess_feather.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/goddess_feather.tex"))
table.insert(Assets, Asset("ANIM", "anim/goddess_deer_build.zip"))
table.insert(Assets, Asset("ANIM", "anim/goddess_lantern.zip"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/goddess_lantern.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/goddess_lantern.tex"))
table.insert(Assets, Asset("ANIM", "anim/goddess_fountain_gem.zip"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/goddess_fountainette.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/goddess_fountainette.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/goddess_rabbit_live.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/goddess_rabbit_live.tex"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/less_bottle_green_milk.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/less_bottle_green_milk.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/peach_juice_bottle_green_less.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/peach_juice_bottle_green_less.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/peach_juice_bottle_green_most.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/peach_juice_bottle_green_most.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/peach_juice_bottle_green_most.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/peach_juice_bottle_green_most.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/peach_juice_bottle_green_half.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/peach_juice_bottle_green_half.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/peach_juice_bottle_green_less.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/peach_juice_bottle_green_less.xml"))
table.insert(Assets, Asset("IMAGE", "images/inventoryimages/bottle_green_youghurt.tex"))
table.insert(Assets, Asset("ATLAS", "images/inventoryimages/bottle_green_youghurt.xml"))
RegisterInventoryItemAtlas("images/inventoryimages/peach.xml", "peach.tex")
RegisterInventoryItemAtlas("images/inventoryimages/grilled_peach.xml", "grilled_peach.tex")
RegisterInventoryItemAtlas("images/inventoryimages/magicpowder.xml", "magicpowder.tex")
-- RegisterInventoryItemAtlas("images/inventoryimages/peachy_meatloaf.xml", "peachy_meatloaf.tex")
RegisterInventoryItemAtlas("images/inventoryimages/peach_juice_bottle_green.xml", "peach_juice_bottle_green.tex")
RegisterInventoryItemAtlas("images/inventoryimages/full_bottle_green.xml", "full_bottle_green.tex")
RegisterInventoryItemAtlas("images/inventoryimages/less_bottle_green_milk.xml", "less_bottle_green_milk.tex")
RegisterInventoryItemAtlas("images/inventoryimages/half_bottle_green_milk.xml", "half_bottle_green_milk.tex")
RegisterInventoryItemAtlas("images/inventoryimages/full_bottle_green_milk.xml", "full_bottle_green_milk.tex")

AddMinimapAtlas("images/map_icons/goddess_statue.xml")
AddMinimapAtlas("images/map_icons/goddess_statue2.xml")
AddMinimapAtlas("images/map_icons/goddess_statue3.xml")
AddMinimapAtlas("images/map_icons/goddess_fountain.xml")
AddMinimapAtlas("images/map_icons/goddess_shrine.xml")
AddMinimapAtlas("images/map_icons/goddess_gate.xml")
AddMinimapAtlas("images/map_icons/peach.xml")
