--渡渡鸟数量控制
_G.SEABEACH_AMOUNT = {
    doydoy = 0,
}

EQUIPSLOTS.BARCO = "barco"

-- TODO 定义新的FUELTYPE最好给图鉴一个图片
-- FUELTYPE_SUBICON_LOOKUP
FUELTYPE.TAR = "TAR"
FUELTYPE.REPARODEBARCO = "REPARODEBARCO"
FUELTYPE.LIVINGARTIFACT = "LIVINGARTIFACT"
FUELTYPE.ANCIENT_REMNANT = "ANCIENT_REMNANT" -- Runar: 在modmain太炸裂了
FUELTYPE.CORK = "CORK"

MATERIALS.SANDBAG = "sandbag"
MATERIALS.LIMESTONE = "limestone"
MATERIALS.ENFORCEDLIMESTONE = "enforcedlimestone"

TOOLACTIONS["HACK"] = true
TOOLACTIONS["SHEAR"] = true
TOOLACTIONS["PAN"] = true
TOOLACTIONS["INVESTIGATEGLASS"] = true



