PrefabFiles = {
  "tropical_boat_lamps",
  "grassnova",
  "axeobsidian",
  "armor_obsidian",
  "meteor_impact",
  "dug_cofeecactus",
  "snake",
  "snake_hole",
  "snakeskin",
  "harpoon",
  "new_hats",
  "parrot_pirate",
  "dubloon",
  "seagull",
  "toucan",
  "mosquitopoison",
  "cormorant",
  "chiminea",
  "sea_chiminea",
  "chimineafire",
  "armor_seashell",
  "ox_horn",
  "ox",
  "oxherd",
  "knightboat",
  "knightboat_cannonshot",
  "rowboat_wake", --trail do rowboat
  "blubber",
  "fish_med",
  "solofish",
  "boatrepairkit",
  "sandbag",
  "cutlass",
  "luggarechestspawn",
  "buriedtreasure",
  "windtrail",
  "windswirl",
  "ventania",
  "boattorch",
  "boatlantern",
  "boatcannon",
  "woodlegs_boatcannon",
  "quackeringram",
  "quackenbeak",
  "quackendrill",
  "quackering_wave",
  "quackering_wake",
  "trawlnet",
  "boatsurfothers",
  "turbine_blades",
  "buoy",
  "armor_lifejacket",
  "luckyhat",
  "telescope",
  "thatchpack",
  "parrot",
  "seagullwater",
  "seaweed_stalk",
  "corallarve",
  "nubbin",
  "coconade",
  "piratepack",
  "ox_flute",
  "blubbersuit",
  "tarsuit",
  "waterchest",
  "mussel_bed",
  "mussel_stick",
  "messagebottle1",
  "bottlelantern",
  "researchlab5",
  "roe",
  "roe_fish",
  "fishfarm",
  "fishfarm_sign",
  "mussel_farm",
  "tar_extractor",
  "seatrap",
  "hail",
  "spearlauncher",
  "speargun",
  "armor_cactus",
  "seasack",
  "magic_seal",
  "wind_conch",
  "sail_stick",
  "armor_windbreaker",
  "vine",
  "lavapool",
  "obsidian",
  "armor_limestone",
  "bermudatriangle",
  "dragoonegg", --jogo da erro de memoria se tirar
  "crate",
  "dragoon",
  "dragoonfire",
  "dragoonspit",
  "dragoonden",
  "dragoonheart",
  "volcano_shrub",
  "flamegeyser",
  "rock_obsidian",
  "magma_rocks",
  "obsidian_workbench",
  "obsidianfirepit",
  "obsidianfirefire",
  "elephantcactus",
  "coffeebush",
  "coffeebeans",
  "coffee",
  "lavaerupt",
  "volcano",
  "woodlegs_cage",
  "woodlegs_key1",
  "woodlegs_key2",
  "woodlegs_key3",
  "woodlegs1",
  "woodlegsghost",
  "woodlegs_unlock",
  "vulcano",
  "escadadovulcao",
  --table.insert(PrefabFiles,"mermfisher",
  "flup",
  "flupegg",
  "tidalpool",
  "poisonhole",
  "tigershark",
  "tigersharkshadow",
  "volcanofog",
  "flupspawner",
  "jungletrees",
  "jungletreeseed",
  "bambootree",
  "bamboo",
  "wildbore",
  "wildborehouse",
  "doydoy",
  "doydoy_mating_fx",
  "doydoyegg",
  "doydoyfeather",
  "doydoyherd",
  "doydoynest",
  "livingjungletree",
  "doydoy_spawner",
  "berrybush2_snake",
  "lavapondbig",
  "bigfoot",
  "glommerbell",
  "sweet_potato",
  "doydoyfan",
  "sand_castle",
  "sandhill",
  "sand",
  "seashell",
  "seashell_beached",
  "rock_limpet",
  "limpets",
  "palmleaf",
  "palmleafhut",
  "palmtrees",
  "coconut",
  "crab",
  "crabhole",
  "treeguard",
  "treeguard_coconut",
  "warningshadow",
  "slotmachine",
  "sharkitten",
  "sharkittenspawner",
  "bush_vine",
  "primeapebarrel",
  "monkeyball",
  "shark_gills",
  "primeape",
  "icemaker",
  "tigereye",
  "packim",
  "packim_fishbone",



  "poisonbubble",
  "tunacan",
  "edgefog",
  "wave_ripple",

  "ashfx",
  "firerain",
  "lavapool",
  "mermhouse_fisher",
  "fabric",
  "coral",

  "seaweed_planted",
  "seaweed",
  "wreck",
  "fishinhole",
  "octopusking",
  "kraken_tentacle",
  "kraken_projectile",
  "kraken",
  "solofish",
  "swordfish",
  "sharx",
  "stungray",
  "redbarrel",
  "lobsterhole",
  "mussel",
  "bioluminescence",
  "rawling",
  "coral_brain_rock",
  "coral_brain",
  "limestone",
  "shark_fin",
  "rainbowjellyfish",
  "rainbowjellyfish_planted",
  "sea_yard",
  "sea_yard_arms_fx",
  "tar",
  "tar_pool",
  "bioluminescence_spawner",
  "ballphin",
  "ballphinhouse",
  "dorsalfin",
  "ballphinpod",
  "jellyfish",
  "jellyfish_planted",
  "crocodog_spawner",
  "crocodog",
  "whale",
  "whale_carcass",
  "jungletreeguard",
  "jungletreeguard_snake",
  -- "ox_wool", --水牛毛
  -- "conch", --海螺
  "krakenchest",
  "spearsw",
  "rookwater",
  "whaletrack",
  "panda",
  "pandaskin",
  "pandatree",
  "floodsw",
  "galinheiro",
  "palmleaf_umbrella",
  "blowdart_sw",
  "piratihatitator",
  "walls_tropical",
  "trident_sw",
  "boatraft",
  "tigersharkpool",
  "tigersharktorch",
  "volcanostaff",
  "armor_snakeskin",
  "mangrovetrees",
  "mangrovetreesbee",
  "grass_water",
  "kraken_jellyfish",
  "kraken_spawner",
  "pirateghost",
  "waterygrave",
  "flotsam_debris_sw",








}




----------------------------------------------------------------------------------------------------


if TUNING.tropical.sealnado then
  table.insert(PrefabFiles, "twister")
  table.insert(PrefabFiles, "twister_spawner")
  table.insert(PrefabFiles, "twister_seal")
  table.insert(PrefabFiles, "twister_tornado")
end
