-- 仙人掌铠甲
TUNING.ARMORCACTUS = TUNING.DEFAULT_CHARACTER_HEALTH * 3
TUNING.ARMORCACTUS_ABSORPTION = .8

--石灰岩甲
TUNING.ARMORLIMESTONE = 150 * 5.5
TUNING.ARMORLIMESTONE_ABSORPTION = .70
TUNING.ARMORLIMESTONE_SLOW = 0.90

TUNING.OBSIDIANAXE_DAMAGE = 27
TUNING.OBSIDIANAXE_USES = 250

TUNING.TRAWLNET_MAX_ITEMS = 9


-- 刮风
TUNING.WINDBLOWN_SCALE_MIN =
{
    LIGHT = 0.1,
    MEDIUM = 0.1,
    HEAVY = 0.01
}
TUNING.WINDBLOWN_SCALE_MAX =
{
    LIGHT = 1.0,
    MEDIUM = 0.25,
    HEAVY = 0.05
}
TUNING.BERRYBUSH_WINDBLOWN_SPEED = 0.2
TUNING.BERRYBUSH_WINDBLOWN_FALL_CHANCE = 0.01

