-- 仙人掌铠甲
TUNING.ARMORCACTUS = TUNING.DEFAULT_CHARACTER_HEALTH * 3
TUNING.ARMORCACTUS_ABSORPTION = .8

--石灰岩甲
TUNING.ARMORLIMESTONE = 150 * 5.5
TUNING.ARMORLIMESTONE_ABSORPTION = .70
TUNING.ARMORLIMESTONE_SLOW = 0.90

TUNING.OBSIDIANAXE_DAMAGE = 27
TUNING.OBSIDIANAXE_USES = 250

TUNING.TRAWLNET_MAX_ITEMS = 9
