TUNING.OBSIDIANAXE_DAMAGE = 27
TUNING.OBSIDIANAXE_USES = 250

TUNING.TRAWLING_SPEED_MULT = 0.75
TUNING.TRAWLNET_MAX_ITEMS = 9
TUNING.TRAWLNET_ITEM_DISTANCE = 100 --How far you have to travel to get another item