PrefabFiles = {
    "lizardman_cave",
    "lizardman",
    "pig_figure.lua",
    "gw_bonestaff",
    "dug_marshberry",
    "greententacle",
    "marshberry",
    "gw_yellow_lizardman",
    "tentacle_attack_spike",
    "gf_lightning_dummy",
    "gf_lightningfx",
    "gw_column_angel",
    "gw_rune",
}
